### ISSUE TITLE
Rebase on Bitcoin Core 0.12.0

### ISSUE THREAD

**Issue by hectorj** [bitcoinclassic/bitcoinclassic#102]
Hi!

Bitcoin Core 0.12.0 is out: https://github.com/bitcoin/bitcoin/tree/0.12

It could be nice to benefit from the new improvements.

How hard is it to rebase Classic work on it?

I'm no C++ developer, but I can give it a try today if no one else is working on it.

**Comment by zander** [comment]
Check our github
