### ISSUE TITLE
CreateNewBlock doesn't check sighash or new sigops in 0.12

### ISSUE THREAD

**Issue by jtoomim** [bitcoinclassic/bitcoinclassic#115]
CreateNewBlock still needs some work in the 0.12 branch to enforce the sighash limit and the properly-counted sigops limit. It's probably impossible to violate the sighash limit without specially-crafted attack transactions that bypass AcceptToMemoryPool (i.e. submitted by RPC), but it should still be checked for. The current code only tests for that in the TestBlockValidity check at the end; if that is violated, then the node will crash entirely, which isn't exactly graceful.

The approach to this that makes the most sense to me is to add two new properties to the CTxMempoolEntry class for bytes hashed and for true sigops, and use those precomputed values during CreateNewBlock to make sure that they are not exceeded by a transaction. This approach requires that every code path by which a transaction can enter the mempool be modified in order to ensure that bytes hashed and true sigops are computed, which is a task that I began but did not finish. 

I started those changes here: https://github.com/jtoomim/bitcoin/commit/6759614e7a3e5742483558353a2d9f84d3b1468f

> This version includes significant differences written by jtoomim
> compared to the commit made for 0.11.2 by Gavin due to the massive
> changes made to CreateNewBlock in Core 0.12. Since transactions are
> no longer validated inside CreateNewBlock in 0.12, the bytes hashed
> and sigops for each transaction cannot be calculated inside
> CreateNewBlock. Instead, they must be precomputed and stored inside
> the CTxMempoolEntry object. This commit is a partial implementation of
> that process. It records the sigops and sighash when transactions enter
> the mempool through AcceptToMemoryPool. However, it does not yet
> do so for transactions that enter via reorgs or via the wallet.
> 
> In addition, the changes made in this code breaks the
> miner_tests.cpp stuff, since that code expects an exception to
> be raised, but this code will simply refuse to include transactions
> that would exceed the sigops/sighash limit. This behavior is okay,
> but it does mean that the unit tests need to be rewritten to
> check for whether the naughty transaction was included in the block
> or not.

The relevant changes are in AcceptToMemoryPool (main.cpp), CreateNewBlock (miner.cpp), and everything in txmempool.h and txmempool.cpp.

This code was based on a slightly different 0.12 branch than the one that is currently in Classic's repository, since I did most of this work before there was a 0.12 branch in Classic's repo. It might not merge well.

**Comment by zander** [comment]
There is a commit under review for some time already which fixes this. Mostly waiting for Gavin to come back from conferences :)

**Comment by zander** [comment]
I'll close this, since we already have a PR for some days. Please check the PRs next time before opening bugreports.

**Comment by jtoomim** [comment]
That PR is https://github.com/bitcoinclassic/bitcoinclassic/pull/108.
