### ISSUE TITLE
DEFAULT_BLOCK_MAX_SIZE

### ISSUE THREAD

**Issue by hikari-no-yume** [bitcoinclassic/bitcoinclassic#121]
This is still set to 750kB in Classic, [despite the problems](https://github.com/bitcoin/bitcoin/pull/7622). Should Classic also consider raising it to 1MB?

**Comment by sandakersmann** [comment]
Already done in https://github.com/bitcoinclassic/bitcoinclassic/commit/76e123a3b3f842a79904c1bfcdc971ee3d388851#diff-4a59b408ad3778278c3aeffa7da33c3cL128

**Comment by hikari-no-yume** [comment]
Ah, alright then! Should the constant be removed, then?

**Comment by zander** [comment]
It could, and technically it should.

But to avoid merge conflicts, I'd leave it.

Leave this PR open for a while, since we now had 2 PRs for this same line in 2 days.

**Comment by hikari-no-yume** [comment]
Yeah, I was thinking merge conflicts might be an issue. Maybe a comment could be added above that line to point out that it's no longer used in Classic?

**Comment by zander** [comment]
> Yeah, I was thinking merge conflicts might be an issue. Maybe a comment could be added above that line to point out that it's no longer used in Classic?

That would still cause a merge conflict :)

**Comment by hikari-no-yume** [comment]
True!
