### ISSUE TITLE
copyright headers to Bitcoin classic

### ISSUE THREAD

**Issue by SartoNess** [bitcoinclassic/bitcoinclassic#128]
Change copyright headers to  // Copyright (c) _year-year_ The Bitcoin **Classic** developers,

**Comment by christophebiocca** [comment]
Last time this was discussed the following was mentionned:
1. Changing copyright headers on every file adds lots of merge conflicts for no benefit.
2. Technically the code originates with bitcoin core, and as such _is_ their copyright.
3. The plan is to append (not replace) to that copyright notice if and when changes are actually made to the file.

**Comment by SartoNess** [comment]
This line must change on next release https://github.com/bitcoinclassic/bitcoinclassic/blob/0.12/src/qt/splashscreen.cpp#L43 to the Bitcoin Classic developers
Next: on eachfile // Copyright (c) 2009 Satoshi Nakamoto
                           // Copyright (c) year:year The Bitcoin Core developers
                           // Copyright (c) year:year The Bitcoin Classic developers

**Comment by zander** [comment]
Thanks for the patch, its been merged. So closing.
