### ISSUE TITLE
What are the rules for protocol changes?

### ISSUE THREAD

**Issue by taoeffect** [bitcoinclassic/bitcoinclassic#13]
Are they the same as Core? I.e.:

> Where a patch set proposes to change the Bitcoin consensus, it must have been discussed extensively on the mailing list and IRC, be accompanied by a widely discussed BIP and have a generally widely perceived technical consensus of being a worthwhile change based on the judgement of the maintainers.

And will Classic adopt (or has it already decided to use) a [rough consensus](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-October/011457.html) model for protocol changes?

And if so, where are protocol changes discussed? (Core uses a mailing list but I can't find one for Classic.)

**Comment by jtoomim** [comment]
This is a good question. We're not sure yet.

https://bitcoinclassic.consider.it/how-to-change-the-code?results=true

That's a draft of how we discuss code and enact code changes, which isn't the same, but related.

For protocol changes, the only thing on the table right now is the 2 MB change and associated consensus rules. That is being discussed all over the place, including consider.it, reddit.com/r/bitcoin_classic, /r/btc, and slack.

**Comment by taoeffect** [comment]
> We're not sure yet.

OK, thanks for the reply. In that case you may want to modify [the document that was forked](https://github.com/bitcoinclassic/bitcoinclassic/blob/master/CONTRIBUTING.md#peer-review) to reflect that until you are.

**Comment by jtoomim** [comment]
Do you have time to submit a PR?

**Comment by taoeffect** [comment]
Sure.

**Comment by jtoomim** [comment]
Great, thanks. You could also maybe collaborate on this with @toomim. It sounds like the kind of thing he would like.

**Comment by taoeffect** [comment]
https://github.com/bitcoinclassic/bitcoinclassic/pull/14

**Comment by orangeman** [comment]
A _closed governance model_ will likely further allienate contributors

**Comment by PaulCapestany** [comment]
+1 (I'm also interested in this issue)

**Comment by toomim** [comment]
@PaulCapestany: Check out CONTRIBUTING.md. A draft of the process just got committed.

**Comment by ripper234** [comment]
This is my proposal:

https://bitcoinclassic.consider.it/choose-someone-as-a-benevolent-dictator

**Comment by zander** [comment]
Not a closed discussion, but really not something that should be discussed on github.
