### ISSUE TITLE
Policy option to autoblock/ban peers that aren't relaying the blockchain, and mask user agent until peer is trusted.

### ISSUE THREAD

**Issue by optimiz3** [bitcoinclassic/bitcoinclassic#130]
I've noticed my node has many peers which aren't actually nodes and consume connection slots.

Many node operators have no interest in subsidizing blockchain hosting for peers that don't return the favor.

Additionally, such peers tend to have no direct value as they tend to not relay transactions.

Sometimes peers are malicious crawlers (as in the recent Classic DDoS scripts), or just actors indexing nodes for their own private gain without returning anything to the network.

IMO we should have the option to "raise the bar" with respect to these peers.

Here are some possible policy settings:

Policy 1: If a peer is not white-listed and doesn't advertise NETWORK, it is disconnected immediately

Policy 1a: If a peer is advertises NETWORK and is not white-listed, request $NUMBER random known block headers, if any of these fail the peer is disconnected immediately, if this succeeds the peer is white-listed for $POLICY time.

Policy 1b: If a peer is advertises NETWORK and is not white-listed, request a random known block, if this fails the peer is disconnected immediately. If a peer succeeds the peer is white-listed for $POLICY time.

Policy 2: If a transaction is sent, and a peer does not request it or store it in its mempool, disconnect the peer immediately.  After the peer requests the transaction, periodically request the transaction from the peer to confirm it is relaying the transaction until the transaction is confirmed.  If the peer evicts the transaction and is not re-requesting the transaction when re-advertised, disconnect the peer as it is providing no value.

Policy 3: If a peer is not white-listed, reply with the same user-agent as the peer.  Once the peer is white-listed, upon re-connect verack responds with the "true" user-agent; alternately a newer verack2 message might be appropriate to disclose the user agent.
*Note: implementation details are just ideas on this one, but the intent is to not reveal the user-agent until the peer is trusted"

**Comment by christophebiocca** [comment]
No opinion on this, but I'll mention that most peers with NETWORK not set are SPV wallets.

**Comment by zander** [comment]
The only thing that such a change will accomplish is that those peers you don't like will start lying about having certain services or having a certain name.

What you suggest is not possible.

**Comment by optimiz3** [comment]
It is possible though - they have to provide proof in terms of blocks and headers.  Perfect is the enemy of the good, and this raises the difficulty of malicious actors.
