### ISSUE TITLE
 ERROR: Read: Failed to open file banlist.dat

### ISSUE THREAD

**Issue by Celean** [bitcoinclassic/bitcoinclassic#137]
Issue appears to have been introduced between v0.11.2 and v0.12.0rc1 and is still present in v0.12.0.

2016-03-08 10:11:57 ERROR: Read: Failed to open file /home/bitcoin/.bitcoin/banlist.dat
2016-03-08 10:11:57 Invalid or missing banlist.dat; recreating

The file is not created, and the error reoccurs on next restart. Installation on this server was fresh,  and the .bitcoin directory has the correct owner and permissions.

Issue appears to be in [this code snippet](https://github.com/bitcoinclassic/bitcoinclassic/blob/0.12/src/net.cpp#L1939). The code for this is different in the master branch. Assuming nothing else has changed with how this is initialized, it seems that the following needs to be changed.

```
if (!bandb.Read(banmap))
    LogPrintf("Invalid or missing banlist.dat; recreating\n");
```

to

```
if (!bandb.Read(banmap)) {
    LogPrintf("Invalid or missing banlist.dat; recreating\n");
    CNode::SetBannedSetDirty(true); // force write
    DumpBanlist();
}
```

**Comment by zander** [comment]
What happens if you try to use the banning functionality?

**Comment by Celean** [comment]
By doing a 

`./bitcoin-cli setban "1.2.3.4" "add"`

the banlist.dat file is indeed correctly created, and the startup error goes away. As such, the only problem here is the reoccurring error on startup before you use this for the first time.

**Comment by ghost** [comment]
i have pull request with some code to fix this.
hopefully this will be included soon

**Comment by zander** [comment]
Fixed in develop branch

**Comment by alex24777** [comment]
How can I read the file: banlist.dat ?
