### ISSUE TITLE
Potential Deadlock?

### ISSUE THREAD

**Issue by C-Otto** [bitcoinclassic/bitcoinclassic#146]
While debugging #97 I noticed this in gdb:

```
bitcoin-qt: sync.cpp:112: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion `onlyMaybeDeadlock' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffa67fc700 (LWP 10780)]
0x00007ffff312f067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

Any idea if this is relevant? It makes debugging for the crash harder, at least.

Commit 6cebccd6965b2825bcb4058caf479daa512c1bb8 (v0.12)

**Comment by zander** [comment]
I watched the output generated (in the debug.log) from several of such potential deadlocks and it looks very much like the assert is wrong. I can't figure out any way in which those traces would actually cause a deadlock.

On top of that, we haven't had any reports of bitcoin having threads hang forever, which is what you'd see if you'd have a deadlock.

I'm going with the conclusion that the assert itself is wrong. At least until more evidence presents itself.
