### ISSUE TITLE
Setup TeamCity as CI / Build Server

### ISSUE THREAD

**Issue by keo** [bitcoinclassic/bitcoinclassic#156]
This is a task list for setting up TeamCity.

Docs and scripts are added to the following branch (WIP): https://github.com/keo/bitcoin/tree/setup-buildserver
- [x] Install Ubuntu Trusty
- [ ] Install Postgresql
- [ ] Setup postgresql
- [ ] Install TeamCity
- [ ] ~~Install apt-cacher-ng~~ Mirrors look like fast enough
- [ ] Configure TeamCity memory usage
- [ ] Setup sharing of artifacts & caching
- [ ] Build Config for PRs (no gitian, build with cached dependencies, run tests)
- [ ] Build Config for Gitian base VM
- [ ] Build Config for nightlies (gitian full build from scratch, run tests, pgp sign artifacts)
- [ ] Report build results to GitHub
- [ ] Slack notification?
- [ ] Match TeamCity username with GitHub usernames
- [ ] Run multiple agents in LXC containers
- [ ] Server security checkup / lockdown
- [ ] TeamCity security checkup / lockdown
- [ ] Setup domain and SSL
- [ ] Docs: finish missing parts in `contrib/ci-scripts/README.md` so anyone can setup their own server and agents
- [ ] Setup regular backup of TeamCity config so we can kickstart a new server in less than a day in case of a disaster
- [ ] Dashboard (outside of TeamCity) with recent build logs
- [ ] Setup personal builds for devs?

**Comment by zander** [comment]
> Setup regular backup of TeamCity config so we can kickstart a new server in less than a day in case of a disaster

How much of the setup and config can be stored in git immediately?

**Comment by keo** [comment]
I think 95% could be easily added to the repo. Maybe more.

**Comment by zander** [comment]
Closing this issue due to lack of progress and I ended up setting up a teamcity myself.
