### ISSUE TITLE
OSX: "make deploy" doesn't work

### ISSUE THREAD

**Issue by lunokhod** [bitcoinclassic/bitcoinclassic#161]
I have successfully compiled bitcoind/-cli from source on OSX, but I am have having problems compiling the qt client, as well as making the install disk image. In short, the make procedure listed below does not make the bitcoin-qt client (which is usually in src/qt), and when I type `make deploy` (which used to work fine before), I get the following errors

```
% make deploy
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src qt/bitcoin-qt
  OBJCXXLD qt/bitcoin-qt
clang: warning: argument unused during compilation: '-pie'
Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/bitcoin-qt] Error 1
make: *** [src/qt/bitcoin-qt] Error 2
```

For info, here is I how I compiled everything: **I really wish that the devs would include this info in the osx_build docs! I have never been able to get bitcoin to compile using brew!**

```
./autogen.sh
cd depends/
./config.guess
make HOST=x86_64-apple-darwin15.4.0
cd ..
./configure --prefix=`pwd`/depends/x86_64-apple-darwin15.4.0
make HOST=x86_64-apple-darwin15.4.0
make deploy
```

**Comment by zander** [comment]
If you ever figure out how to build on MacOS, please update the docs.  In the mean time I suggest developing on Linux.
