### ISSUE TITLE
lookahead priority for chainTXs

### ISSUE THREAD

**Issue by ghost** [bitcoinclassic/bitcoinclassic#166]
details: https://www.reddit.com/r/btc/comments/4h1rmd/23k_transaction_stuck_despite_paying_the/d2ncsxk

tl;dr if a transaction depends on another transaction, its priority should go to that transaction.

**Comment by zander** [comment]
New features are great to have, but lets not discuss bitcoin consensus-layer improvements here. They should be agreed with by all implementations.
