### ISSUE TITLE
Lets do it Wright, it's time to stand with Satoshi

### ISSUE THREAD

**Issue by eruddles** [bitcoinclassic/bitcoinclassic#167]
Dr. Craig Wright, previously known as to our community as "Satoshi" has returned to set things right and put Bitcoin back on the path of his original vision. Gavin has confirmed the identity beyond doubt.

It is time for us to stand behind Wright and the Original Vision. He should be appointed head of classic governance and ownership of the github. This will distinguish classic from the Core Cowards and help get the Bitcoin price back on track.

**Comment by christophebiocca** [comment]
Brand new account.

**Comment by zander** [comment]
Please do stand behind the original vision, and I know that many do.

One of the classic visions is that we don't appeal to authority. Everyone gets to make up his own mind. Everyone gets to decide what is best for him/her. Nobody should be believed on their word, the code and crypto should speak for itself.

Craig Wright coming out as Satoshi is entertainment, but I don't feel like bowing down and giving him the keys of the castle. That would be the antithesis of Bitcoin.
