### ISSUE TITLE
License and Attribution

### ISSUE THREAD

**Issue by krisives** [bitcoinclassic/bitcoinclassic#171]
What is the plan for attribution regarding places where it currently says "Bitcoin Core Developers"? 
- is there going to be a new group name like "Bitcoin Classic Developers" which is appended to the source files giving 3 author attributions (Satoshi, Core, and the new group)
- What should the About dialog display? Right now it says "Bitcoin Core Developers"

Another user started a [reddit post](https://www.reddit.com/r/btc/comments/4m6ohy/this_should_be_fixed_imo/d3szyrl) about this topic.

**Comment by krisives** [comment]
Some answers come from #128 but it's not clear if this affects the binary about dialog, all source files, or both.

**Comment by hairthing** [comment]
Since no one holds the copyright, maybe it should look more like the liner notes to [Thriller](https://en.wikipedia.org/wiki/Thriller_(Michael_Jackson_album))

```
Brian Banks – keyboards, synthesizer (track 4), synthesizer programming (2)
Michael Boddicker – keyboards, synthesizers (tracks 1–2), Emulator (6–9), Vocoder (8)
N'dugu Chancler – drums (tracks 2, 6, 8)
Paulinho da Costa – percussion (tracks 1, 7)
David Foster – synthesizers, synthesizer arrangements on "The Girl is Mine"
Gary Grant – trumpet, flugelhorn (tracks 1–2, 4)
Eddie Van Halen – guitar solo on "Beat It"
Jerry Hey – trumpet (tracks 1–2, 4), flugelhorn (1–2, 4), horn arrangements (1–2, 4), string arrangements (3, 6), strings conductor (3)
Michael Jackson – co-producer (All tracks), lead vocals (All tracks), drum case beater (track 5), bathroom stomp board (1), background vocals (1, 4–6), handclaps (8), vocal arrangements (1, 3, 5–6), rhythm arrangements (1, 5–6), horn arrangements (1), synthesizer arrangements (6)
Paul Jackson, Jr. – guitar (tracks 5, 8–9)
Louis Johnson – bass guitar (tracks 1, 3, 6, 8–9)
Quincy Jones – producer (All tracks), rhythm arrangements (tracks 1, 3, 5), vocal arrangements (3), musical arrangements (8)
Steve Lukather – guitar (tracks 3, 5, 7), bass guitar (5), musical arrangements (7)
Anthony Marinelli – synthesizer programming (tracks 2, 4)
Paul McCartney – vocals on "The Girl Is Mine"
David Paich – keyboards, synthesizers (tracks 2, 7, 9), piano (3), rhythm arrangements (3), musical arrangements (7)
Dean Parks – guitar (tracks 3, 6)
Greg Phillinganes – keyboards (track 2), synthesizers (1–2, 4–6, 8), electric piano (3, 6, 9), synthesizer programming (8)
Jeff Porcaro – drums (tracks 3, 5, 7, 9)
Steve Porcaro – keyboards, synthesizers (tracks 5, 7, 9), synthesizer programming (2–3, 5, 7), musical arrangements (7)
Vincent Price – voice-over on "Thriller"
Bill Reichenbach – trombone (tracks 1–2, 4)
Bruce Swedien – recording engineer (All tracks), audio mixer (All tracks)
Chris Shepard – vibraslap on "Beat It"
Rod Temperton – keyboards, synthesizers (track 4), rhythm arrangements (2, 4), vocal arrangements (2, 4), synthesizer arrangements (2, 4)
David Williams – guitar (tracks 1–2, 4)
Larry Williams – saxophone, flute (tracks 1–2, 4)
Bill Wolfer – keyboards (track 5), synthesizers (1, 6), synthesizer programming (6)
La Toya Jackson – background vocals on "PYT"
Janet Jackson – background vocals on "PYT"
Greg Smith – additional synthesizers on "Billie Jean"
```

**Comment by zander** [comment]
> What is the plan for attribution regarding places where it currently says "Bitcoin Core Developers"? 

We follow the law.
Here is a good [description](http://www.gnu.org/licenses/gpl-howto.en.html)

> Whichever license you plan to use, the process involves adding two elements to **each source file** of your program: a copyright notice (such as “Copyright 1999 Terry Jones”), and a statement of copying permission, saying that the program is distributed under the terms of [the license]
> 
> The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). **You should add the proper year for each release**; for example, “Copyright 1998, 1999 Terry Jones” if some versions were finished in 1998 and some were finished in 1999. **If several people helped write the code, use all their names.**
> 
> For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage.
> 
> Always use the English word “Copyright”; by international convention, this is used worldwide, even for material in other languages. The copyright symbol “©” can be included if you wish (and your character set supports it), but it's not necessary. There is no legal significance to using the three-character sequence “(C)”, although it does no harm.

The Bitcoin Core group didn't follow these rules very well. It essentially did not honour copyright of individual contributors, instead giving it all to the group as a whole.

In Classic I think we can improve upon this and grant copyright to individuals in the files they edited.

The question of what to do with the copyright notice we inherited from Core is not easy to answer. Legally individuals still have their rights, but because they never claimed it they will have a really hard time claiming their rights.

I personally don't want to touch their copyright notices as they are none of my business. I can't remove such a notice, even if I deem the entity claiming rights not existing, because I would destroy what little evidence there is of their ownership.

My personal position is that we should add, as suggested by the Free Software Foundation international lawyers which I quoted above, and not remove or change any of the notices in Bitcoin Classic.

**Comment by krisives** [comment]
> My personal position is that we should add, as suggested by the Free Software Foundation international lawyers which I quoted above, and not remove or change any of the notices in Bitcoin Classic.

Does this mean add individuals names instead of a group? That seems a bit messy but I guess licenses don't care about mess.

What about the about dialog?

**Comment by zander** [comment]
> Does this mean add individuals names instead of a group? 

Yes, that is how I understand the law to work.
