### ISSUE TITLE
Why not added support Thinblock?

### ISSUE THREAD

**Issue by arruah** [bitcoinclassic/bitcoinclassic#173]
With all the advantages of this technology, I do not understand why it is still not supported in Bitcoin Classic.

**Comment by Polve** [comment]
I think Classic is created in a way to have the smallest possible changes to core to enable 2MB blocks, to be as uncontroversial as possible.

If you want all kind of new features you can use Bitcoin Unlimited.

**Comment by zander** [comment]
We have a pull request open for this and some more work is going on. The reason it has not been added yet is because we are working to finish other things first.

The next feature release may very well see the xthin blocks support integrated.

**Comment by zander** [comment]
Now in develop

**Comment by rebroad** [comment]
Very happy to see xthin added. @zander are you open to having compact blocks support added too? (with a command line option to enable it)? (as an OT question - would you also consider a command line option to disable the consensus differences between classic and core? I'd be much more inclined to develop for Classic if so,)

**Comment by zander** [comment]
Hi @rebroad 

I'm not sure why adding compact blocks would be beneficial. Especially if its hidden behind a command line option, then the code needed will be tested even less and bug will creep in. Not worth the maintenance headache.

> would you also consider a command line option to disable the consensus differences between classic and core?

There is no practical difference in consensus between classic and core. What do you think that this command line option would enable?

**Comment by rebroad** [comment]
@zander well, for one, it would allow me to connect to the same testnet as core.... hopefully!

I notice there are some nodes out there supporting thin and compact blocks. Ok, perhaps the command line option could be set to be on by default - or rather, it can switch to compact blocksif the connected node states that it prefers compact blocks (the SENDCMPCT message), otherwise defaulting to xthin.

By speaking both languages, it makes Classic nodes presumably more useful in propagating blocks to all nodes of all languages.

**Comment by zander** [comment]
> By speaking both languages, it makes Classic nodes presumably more useful in propagating blocks to all nodes of all languages.

You make it sound like Core is incompatible to Classic. This is not true, blocks can be propagated just fine between them. There are no incompatibilities between them. Please join us on IRC or slack if you are still unconvinced. Github really isn't useful as a discussion forum.
