### ISSUE TITLE
Httplib.badstatusline

### ISSUE THREAD

**Issue by ShawnKimble** [bitcoinclassic/bitcoinclassic#174]
http://www.multichain.com/qa/751/bitcoinrpc-python-wrapper-returns-httplib-badstatusline

I'm seeing this same issue in classic 0.12.1

**Comment by ShawnKimble** [comment]
It appears the issue is that the connection timed out, and re-authentication is required.  The error None, makes this difficult to debug.

**Comment by ShawnKimble** [comment]
Additionally the default timeout in authproxy.py is set to 30 seconds, which may not work for all applications.

**Comment by zander** [comment]
This looks like issues in the python wrapper, not in bitcoin classic.
