### ISSUE TITLE
Missing OpenSSL headers when compiling from source

### ISSUE THREAD

**Issue by dopeideas** [bitcoinclassic/bitcoinclassic#178]
I'm trying to compile bitcoin classic from source on OSX. I've run into a few errors and package issues, but was able to get around them. Now I'm stuck.

Running ./configure works well for most of the processes, but I get stuck on OpenSSL.

```
.....
checking for SSL... yes
checking for CRYPTO... yes
checking for PROTOBUF... yes
checking for QR... no
checking for RAND_egd in -lcrypto... yes
checking openssl/ec.h usability... no
checking openssl/ec.h presence... no
checking for openssl/ec.h... no
configure: error: OpenSSL ec header missing

```

Is the issue that OpenSSL or an alternative SSL handler is running a non-compatible version?

Running:

`./configure --help | grep -i ssl`

Provides me with some insight:

```
  --with-libressl         Build with system LibreSSL (default is no;
 SSL_CFLAGS  C compiler flags for SSL, overriding pkg-config
  SSL_LIBS    linker flags for SSL, overriding pkg-config
 Users-iMac:bitcoinclassic User$ 
```

I previously installed kpg-config with brew as one the missing packages/earlier errors I encountered. It looks like the fact that pkg-config is being overridden is causing this error.

Could someone confirm this is the case? I've overcome the other issues I faced when trying to set this up but I'm stuck here and could use some guidance.

I apologize if this is an incorrect usage of the Issues section since this is likely an issue with my OS and not bitcoin classic. I'm a novice trying to learn.

**Comment by pdpi** [comment]
Can you tell me which version of OSX you're running? Also, could you give me the output of running this: `find /usr -iname "libssl*"`? Thanks!

**Comment by pdpi** [comment]
It seems that newer versions of OSX don't ship with OpenSSL any more — instead, they ship with SSH compiled against LibreSSL, and use [their own TLS](https://developer.apple.com/library/mac/documentation/Security/Reference/secureTransportRef/index.html) implementation elsewhere.

I suggest you try installing openssl from Homebrew, MacPorts, or whichever your package manager of choice is.

**Comment by zander** [comment]
Thanks pdpi, that looks like it answers the question. I'll close this for now "waiting for more information".
dopeideas, feel free to reopen if you fail to find a solution.
