### ISSUE TITLE
Use linux-standard-base standard dir for config file.

### ISSUE THREAD

**Issue by zander** [bitcoinclassic/bitcoinclassic#179]
The standard place where config files on linux go is ~/.config/share/[appname]/

this should be made the default with proper fallback to the current default (~/.bitcoin).

This change should only affect Linux compiles.

**Comment by paketo** [comment]
[removed email address]

**Comment by zander** [comment]
Why did you add an email address in a comment, on a closed task? I removed it, as it doesn't look like it is your email address.
