### ISSUE TITLE
Unable to run on testnet

### ISSUE THREAD

**Issue by rebroad** [bitcoinclassic/bitcoinclassic#188]
I have just encountered an odd situation. I am able to run Bitcoin Core on the testnet, but for some reason Classic is giving errors during the rescan of the last 51 blocks (from block 928580). I read somewhere that a hardfork happened. Might this be due to that? Is there any plan to switch back to one fork on testnet, and if not, does this mean I need two separate data directories? I do think a testnet where Classic is seperate from Core isn't much of a useful testnet - surely interoperability is something that needs testing.

**Comment by zander** [comment]
I have not investigated, but I do think you are right that some fork happened on testnet.

It is important to realize that on testnet a situation happened which is impossible on mainnet. We have a broken BIP109, SegWit and FlexTrans all "active" at the same time. These were not designed to work together, nobody is going to put effort into them working together.

I don't know what the best solution is, I don't really have much mining hardware anyway so my opinion is not that important.

**Comment by rebroad** [comment]
@zander With further testing, I'm not sure if it necessarily was a fork, but there does appear to be a bug, which causes bitcoin classic to crash (and not bitcoin core). It seems to occur at block 869424:-

2016-10-06 20:25:45 UpdateTip: new best=00000000002aecab8a6ddacb5d0aae6750e49f4832e0e3ed8adc34fd5ffc2883 (869424) log2_work=67.488677 tx=10290140 date=2016-06-10 12:41:08 99.656187% cache=17.0
MiB(41330tx)
2016-10-06 20:25:45 ERROR: ReadBlockFromDisk: Deserialize or I/O error - ReadCompactSize(): size too large: iostream error at CBlockDiskPos(nFile=47, nPos=84581589)

This was downloading the entire blockchain using classic only.

**Comment by zander** [comment]
This should be fixed in the daily builds.

**Comment by rebroad** [comment]
@zander Good news! Could you reference the PR/commit that fixed it?

**Comment by rebroad** [comment]
FYI, I have been working on some patches that improve the debug info in debug.log which help the observer of the debug.log understand what it going on on testnet! Will rebase/PR them sometime soon (currently rebased for Bitcoin Core).

**Comment by zander** [comment]
> FYI, I have been working on some patches that improve the debug info in debug.log which help the observer of the debug.log understand what it going on on testnet! Will rebase/PR them sometime soon.

When is "sometime soon"?

**Comment by rebroad** [comment]
b8ba362bb3a25f48e2af4c5f96f5961a819919b1 - for a sneek-peek
