### ISSUE TITLE
Bitcoin Unlimited/XThin Sendheaders quirk may result in extra roundtrip from Bitcoin Core

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoinclassic/bitcoinclassic#189]
Bitcoin Core will likely stop requesting directly from INV requests soon (well, in the next release in a few months, see https://github.com/bitcoin/bitcoin/pull/8872 for more details on why), however this will add a round-trip in propogation between Bitcoin Classic and Bitcoin Core nodes due to a quirk in sendheaders handling in BC.
In reading the XThin code, it seems to me that the check for setting fPreferHeaders is done twice (sendheaders messages are both not sent and not processed if IsThinBlocksEnabled()) , so it should be safe to remove the check in sendheaders receiving, allowing Bitcoin Core nodes to receive headers announcements which they will request for immediately while still allowing XThin nodes to skip sendheaders and receive the inv messages they want to request XThin blocks.

See https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/111 for a proposed fix upstream (I guess BU is upstream since they wrote that code?).

**Comment by zander** [comment]
Followed upstream on this issue.
