### ISSUE TITLE
Proposal - suitable venue for bitcoin development discussion

### ISSUE THREAD

**Issue by rebroad** [bitcoinclassic/bitcoinclassic#193]
bitcoin#9149

I've raised the above issue on Core as I noticed that non-core issues, e.g. protocol changes were being discussed on the group designed for bitcoin core development. I am aware that there is an email list, but this doesn't allow for such real-time discussion, whereas IRC does, but then excludes people unable to attend the meeting at the precise time it occurs. Something between the two seems to be needed.

For the overall health of the network (and to avoid partitioning) I think it is desirable for some co-ordination between bitcoin clients.

Any suggestions?

**Comment by zander** [comment]
Lets keep the bug/issue system here for actual issues...
