### ISSUE TITLE
bitcoin-qt: main.cpp:2297: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed. Aborted

### ISSUE THREAD

**Issue by C-Otto** [bitcoinclassic/bitcoinclassic#198]
I get the following issue when starting my client:

```
bitcoin-qt: main.cpp:2297: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.
Aborted
```

Before several odd things happened:
 - I had to reboot my system (CPUs were stalled according to some console output)
 - When starting bitcoin-qt, I was asked to rescan the blockchain (reindex?), which I confirmed
 - This failed
 - Files in bitcoin's chainstate directory were corrupted
 - I repaired the filesystem
 - Now the issue above appears

Bitcoin version v1.1.1 (2016-09-16 12:26:32 +0200)
Linux 4.8.0-0.bpo.2-amd64 #1 SMP Debian 4.8.11-1~bpo8+1 (2016-12-14) x86_64 GNU/Linux

**Comment by C-Otto** [comment]
I am now running with `-reindex`, which doesn't crash immediately. This could take a while, though :)

**Comment by zander** [comment]
We use 'levelDB' which is not very resistant to corruption and recovery seems to have failed for you.

I hope your machine still had the full blockchain untouched and your machine can indeed just recover with doing a reindex which essentially re-generates the chainstate directory. You may consider just removing your chainstate dir to avoid problems. Notice that this starts the index again.

I'll check the assert, it would be nice if your kind of failure was handled better.

I highly recommend changing the database cash to something higher than the standard 300MB in the initial sync. Think gigabytes instead, if you have it.

Thanks, and good luck!

**Comment by C-Otto** [comment]
Thank you, I'll make use of my 16 GByte of RAM then :)

**Comment by C-Otto** [comment]
```
$ bitcoin-qt -reindex -dbcache=10384
Segmentation fault
```

That happened with those log lines at the end:
```
2016-12-22 04:26:35 UpdateTip: new best=00000000000000000178f4df16be9d22e2ac17596871a33ae35f05a3b02356aa  height=444521  log2_work=85.70887  tx=181068156  date=2016-12-22 03:00:45 progress=0.999976  cache=2434.9MiB(3365996tx)
2016-12-22 04:26:35 UpdateTip: 33 of last 100 blocks have unexpected version
```

Restarting bitcoin-qt without arguments works ("2 weeks behind"). Let's see...

**Comment by C-Otto** [comment]
The node is fully synchronized again.
