### ISSUE TITLE
How classic is compatible with core?

### ISSUE THREAD

**Issue by abueide** [bitcoinclassic/bitcoinclassic#199]
I'm looking for a reliable source that describes when and how bitcoin classic will activate 2 MB blocksizes, and for how long it will be compatible with core clients. I've been looking around for an official source, but can't find any.

**Comment by zander** [comment]
take a look at
https://bitcoinclassic.com/devel/Blocksize.html

-- 
Tom Zander
Blog: https://zander.github.io
Vlog: https://vimeo.com/channels/tomscryptochannel

**Comment by zander** [comment]
Let us know if there are any open questions!
