### ISSUE TITLE
Remove 'using namespace std;' usage in the code.

### ISSUE THREAD

**Issue by zander** [bitcoinclassic/bitcoinclassic#210]
There are various places (please focus on small files!) where the above statement occurs.

The effect of this statement is that code can be written like
`string a("bla");`
instead of
`std::string("bla");`

Since Bitcoin Classic wants to move more in the direction of a proper C++ codebase instead of the C-like code we have today it is beneficial to re-instate the usage of `std::` where they have been removed today.

There is a LOT of code today that could be changed. Please don't feel you need to do all of this, just do one small file at a time so we can run them though unit tests and compile etc to slowly move the codebase in the future.

I will not accept a one-immense-change PR as quality of code is important. Take is slow, be careful and make sure we don't introduce any bugs.

**Comment by 1337ninja** [comment]
Hello @zander I would like to work on this as well although I have one question. Instead of removing using namespace std and making string as std::string, would making

**Comment by 1337ninja** [comment]
@zander I would like to work on this as well but although I am curious about one thing. Given that removing using namespace std is the goal, why didn't you consider using the **using** directive, (using std::vector) **instead of prefixing with std** (std::vector) since the former approach could result in relatively lesser amount of changes. Is there any significant advantage of the latter over the former?

**Comment by zander** [comment]
> Given that removing using namespace std is the goal

No, that wasn't the goal. I thought I explained this in the issue. Here is a relevant quote;

> it is beneficial to re-instate the usage of std:: where they have been removed today.

The goal is to make code more readable and we follow the part of least surprises to reach that.

Being consistent between files about using 'std::map' instead of 'map' helps moving code between files, helps readability because of consistency and purely practical; it avoids situations where the extremely generic names of std classes (without their prefix) would end up conflicting with local variable names.

Cheers

**Comment by 1337ninja** [comment]
I understand. Thanks for making this clear. I'll now work on sending a PR for this.

**Comment by gubatron** [comment]
[Done here](https://github.com/bitcoinclassic/bitcoinclassic/pull/290)
