### ISSUE TITLE
Segregated Witness as hard fork

### ISSUE THREAD

**Issue by orangeman** [bitcoinclassic/bitcoinclassic#23]
SegWit got deleted from bitcoin classic https://github.com/bitcoinclassic/bitcoinclassic/pull/8.
Is anyone already working on SegWit as a hard fork?
Since we are forking hard anyway why not integrate it now?

**Comment by jameshilliard** [comment]
If we are going to do a hard fork we should pull in any non-controversial [hard fork wishlist changes](https://en.bitcoin.it/wiki/Hardfork_Wishlist) as well.

**Comment by jtoomim** [comment]
Merge window is open only for 2 MB HF stuff. 

We do not have the developer resources to dedicate to writing a SW hard fork for you. 

No hard fork or soft fork changes that would break compatibility with thin wallets will be allowed at this time.

If the developers of SegWit wish to collaborate on making a combined hardfork a reality, we can hold a vote about reversing the 2 MB HF merge window rule.
