### ISSUE TITLE
Failsafe mode to turn off the performance improvement

### ISSUE THREAD

**Issue by nfujimoto** [bitcoinclassic/bitcoinclassic#240]
The thin block and parallel validation are nice features to have. However, in case of some bugs in the code, like the recent one, it is easier to turn them off quickly. Are there any plan to implement it? Or is the current system too tightly coupled to implement it easily? Since the most important part is the user adjustable blocksize. So if the client can still run without addition performance improvements, it should greatly improve the stability of the whole network.

**Comment by zander** [comment]
I'm wondering if you unintentionally opened this on the wrong project, Classic doesn't even have a parallel validation.

In any case, there are already options to turn off things like xthin blocks.

**Comment by zander** [comment]
Noticing you posted on the BU site suggesting they have a keep-it-simple release.

In Classic we are following the KISS principle and there is very little changed. There is no AD, just EB in Classic, for instance. xthin can be turned off quite easy and features like FlexTrans are even turned off by default. Having no effect on actual run time.  Please also read https://zander.github.io/posts/ClassicQuality/

**Comment by nfujimoto** [comment]
Sorry, I did not know this. I have this impression because I remember during the last attack, you only advise the people to update to the new client. If the option exist, you should let people know this as an alternative because not everyone can adopt/recompile immediately. I may be completely wrong if you have done this.
