### ISSUE TITLE
Fuck yourself

### ISSUE THREAD

**Issue by jonaschnelli** [bitcoinclassic/bitcoinclassic#241]
Fuck off, no one wants a hard fork

**Comment by NiKiZe** [comment]
zander keep up the good work, your and the BU teams efforts will eventually save the future of Bitcoin.

**Comment by rickw** [comment]
Nice try, this is a fake user who joined 5 hours ago. The user name is missing one s.

**Comment by tulip0** [comment]
Note that this is a different account to the Bitcoin Core developer, though they look alike @jonaschnelli is not @jonasschnelli.
