### ISSUE TITLE
Mempool saving feature between restarts

### ISSUE THREAD

**Issue by ghost** [bitcoinclassic/bitcoinclassic#251]
Bitcoin core 0.14 has a mempool saving feature that saves the mempool states between restarts. This is a very useful feature for people who multiboot between O/S's. (and also in the event of a system crash for miners.) I think this would be useful to add to bitcoin classic.
I am not familiar with this part of the code, but I would look to implement the transaction pool in a virtual memory segment using mmap(), msync(), munmap() if possible. This would mean that all transactions are immediately loaded into virtual memory on start up when the memory segment is mapped onto.

**Comment by zander** [comment]
A couple of thoughts.

* A memory pool in normal situations would not be useful anymore even an hour after the mempool is saved. This is because in normal circumstances practically all of the transactions in a mempool will have been mined by then.
* I honestly don't see the benefit for a non-miner, partly because of the previous point.
* A miner that runs his full node on a machine or operating system which depends on this kind of features is doing it wrong. They should take a more stable OS and/or hardware.

This sounds like a very intrusive 'feature'. And I put the word "feature" in quotes because it is a rather big change in systems design. 

In Classic we are aiming to make the system design more consistent and more robust with the end result that it becomes the most fun-to-hack-on client.  
I'm not sold on this "feature".

**Comment by ghost** [comment]
I'd agree that in normal circumstances, and where blocksize limits are dynamic enough, the mempool should not need to be so persistent. However, there is always the potential for mempool floods (and ways that could be implemented to mitigate any sudden growth).
Core have not yet removed the coin age prioritisation feature. This may mean a mempool with uptime may contain transactions that at some point would be included. I don't know if you intend to follow core in removing this feature.
I have a dislike for forgetful mempools. It destroys the zero confirmation economic risk when block sizes become full, shifting the risk from a disadvantageous double spend propagation attempt, to one where the risk is that the transaction does not confirm at all, due to mempool forgetfulness and selective transaction relay by nodes. People can then double spend once the transaction has been dropped from nodes mempools. I don't believe they should be dropped, they should eventually be confirmed.
I tend to dislike the notion of a mempool. I prefer to call it a transaction pool. Using an lmdb virtual memory database might be a better way to implement this, but performance requirements need to be considered.
I suppose miners have quite robust systems and failover backups, so if one mining node goes down it probably will not have much of a effect on transaction processing, although there is a potential that a miner may produce an empty block. Would such a feature be useful to economic nodes?
I'd be interested to understand why you find this feature 'intrusive'. Also, is the core 0.14 a significant change? If such an approach is desirable, they might not have implemented it in the best way either.

**Comment by zander** [comment]
> Core have not yet removed the coin age prioritisation feature.

This is an essential feature to avoid the "tragedy of the commons" problem, and as such will not be removed.

> I have a dislike for forgetful mempools. 

I understand, and this is an area that definitely is in need of more empirical evidence. Core is steadily moving towards the idea that all mempools are the same, essentially making each full node a duplicate instance of the next.  
The other extreme is a highly distributed mempool where massive distributed mempool means one mempool dropping a transaction doesn't hurt as there are many others that still have it.

We are at neither extreme, for instance only the originator of a transaction re-broadcasts it periodically. Nodes don't re-broadcast their mempools.

Innovation in this area is needed, but I hope we can do a proper research project with thousands of (virtual) nodes emulating the different methods and finding out how things actually work and thus get some actual empirical evidence which we can use to decide what features we need to benefit the health of the mempool.

> I'd be interested to understand why you find this feature 'intrusive'. 

Going from a hashmap to a format that can be stored in a memmapped file will have a big impact on a lot of common calls being made to the mempool right now.  
Next to that, you need to have a way to identify false data. Half writes, etc.

Personally I doubt the mempool being memmapped makes sense. There are better architectures for that. A log of validated transactions and subsequently invalidated ones is much much easier and at least as effective.

**Comment by ghost** [comment]
Thank you for your comments and insights. I think I agree that this is probably an area that requires extensive research and innovation.

I have opened similar issues on BU and XT, so it will be interesting to see their thoughts on this matter.

https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/438
https://github.com/bitcoinxt/bitcoinxt/issues/195

**Comment by zander** [comment]
Probably the best way to implement this feature is to add support to the [AdminServer](https://bitcoinclassic.com/devel/AdminServer.html) for notification of new transactions being added to the mempool.

Then create a separate app that logs the transactions which can then replay the log by adding them to a newly started node using the same admin server.

**Comment by ghost** [comment]
The NetworkManager, Compact Message Format and AdminServer looks like a good innovation at first glance with my limited in-depth knowledge of the bitcoin software.

Going back to the zero confirmation economic risk transaction, it only works on the condition that they will eventually get confirmed. If transaction pools are forgetful, then there is a reliance on the sender to re-broadcast the transaction. Having all transaction pools re-broadcasting transactions periodically would lead to a lot of network traffic. I'm also wondering if nodes could come to a consensus about the validity of a transaction before a miner includes it in a block. That is, if a user attempts to double spend quickly, nodes could flag the transaction invalid. If the double spend attempt is after a period of time, the original transaction will have propagated the network and so the original transaction would be considered the valid one. If nodes can come up with consensus within a second or two, and a way found so that the transaction is never dropped and  eventually will be confirmed with guarantee, we have solved instant transactions with very little economic risk.

**Comment by zander** [comment]
> That is, if a user attempts to double spend quickly, nodes could flag the transaction invalid.

This is a feature in [FlexTrans](https://bitcoinclassic.com/devel/Flexible%20Transactions.html). See [Double spend proofs](https://bitcoinclassic.com/devel/Double%20Spend%20Proofs.html).

**Comment by ghost** [comment]
Knocking some dust out of my brain cells this is. I think you are correct that saving a mempool on a node is a stupid idea. If a node is down for any length of time its transaction set is so out of date it's not worth the effort checking what is in a block. In it's downtime, many transactions have been missed. If the node crashes, a vm based solution would need check pointing and transaction logs to be of any use.

If the node network consists of many high up time nodes, then the chance for a double spend to get through is minimal. However, if there are many part time nodes, there is a chance for a double spend to get through between sender and recipient, which may get rejected by the miners nodes.

So perhaps it would be better for a newly started node to obtain it's transaction pool from it's peers? The idea of perfectly synchronised transaction pools is probably a fruitless endeavor in an asynchronous peer to peer system. But a system where the transaction pools are close enough to synchronisation is probably enough to reduce the chance of a double spend getting through.

**Comment by ghost** [comment]
gmaxwell as outlined the idea behind this feature.

https://bitcointalk.org/index.php?topic=1864311.0

**Comment by zander** [comment]
Thanks for asking there.

I liked gmaxwells conflicting statements;

> Without saving the sync would be a _massive_ waste of bandwidth

and just a couple lines lower;

> Efficient syncing is also an active area of research, there are techniques to perform the sync in ways which are significantly more efficient than you might guess.

The main reason he states it would be wasteful is because the current p2p protocol is very naive and is not really capable of being optimized.  A AdminServer based sync would be very cheap, however.

**Comment by ghost** [comment]
Politician or Ambassador?

I'm not entirely convinced about his arguments regarding periodically flushing. Firstly, the file save is written to mempool.dat.new, and then moved to mempool.dat. It could write timestamped mempool.dat files, and then the software could load the last known good file. Not sure if the CAutoFile class provides any from of file validity, e.g. checksumming at this moment in time.

SSD's are also pretty tough these days. My four year old SSD is still running after four years of uptime hammering with only 8 bad sectors. I've had 2 mechanical disks fail in the same timeframe.

I do like your compact message format. It could be possible to build something similar to FIX protocol (Financial Information eXchange) on top of it. Cryptocurrency exhanges have the same problem with https/JSON REST queries which have to be polled, and a lack of a common standard and behaviour to build solid software that connects to multiple exchanges.

**Comment by ghost** [comment]
Any closure notes on this?

**Comment by zander** [comment]
I'm going to quote you;
> Knocking some dust out of my brain cells this is. I think you are correct that saving a mempool on a node is a stupid idea. 

Sounds like sufficient reason to close this feature request to me...

**Comment by ghost** [comment]
Fair enough. I suppose as long as the idea that perhaps transaction pools on newly started nodes should efficiently sync from their peers is on peoples thought radar (due to the potential double spending holes or empty block mining that it may cause) then I am happy for it to be closed.
