### ISSUE TITLE
Minimize to tray not recovered from fully on Ubuntu 

### ISSUE THREAD

**Issue by ghost** [bitcoinclassic/bitcoinclassic#265]
Bitcoin Classic version v1.2.5.0-18bd3372 (64-bit)
* compiled from source
Ubuntu: 17.04
Desktop environment: Unity
unity:
  Installed: 7.5.0+17.04.20170407.1-0ubuntu1
  Candidate: 7.5.0+17.04.20170407.1-0ubuntu1
libqt5core5a:
  Installed: 5.7.1+dfsg-2ubuntu4\~1
  Candidate: 5.7.1+dfsg-2ubuntu4\~1
  Version table:
 *** 5.7.1+dfsg-2ubuntu4\~1 500
        500 http://ca.archive.ubuntu.com/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status
libqt5dbus5:
  Installed: 5.7.1+dfsg-2ubuntu4\~1
  Candidate: 5.7.1+dfsg-2ubuntu4\~1
  Version table:
 *** 5.7.1+dfsg-2ubuntu4\~1 500
        500 http://ca.archive.ubuntu.com/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status
libqt5gui5:
  Installed: 5.7.1+dfsg-2ubuntu4\~1
  Candidate: 5.7.1+dfsg-2ubuntu4\~1
  Version table:
 *** 5.7.1+dfsg-2ubuntu4\~1 500
        500 http://ca.archive.ubuntu.com/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status
libqt5network5:
  Installed: 5.7.1+dfsg-2ubuntu4\~1
  Candidate: 5.7.1+dfsg-2ubuntu4\~1
  Version table:
 *** 5.7.1+dfsg-2ubuntu4\~1 500
        500 http://ca.archive.ubuntu.com/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status
libqt5widgets5:
  Installed: 5.7.1+dfsg-2ubuntu4\~1
  Candidate: 5.7.1+dfsg-2ubuntu4\~1
  Version table:
 *** 5.7.1+dfsg-2ubuntu4\~1 500
        500 http://ca.archive.ubuntu.com/ubuntu zesty/main amd64 Packages

Steps to reproduce:

1)  set 'minimize to task bar':
i) go into options -> window -> put checkmark in minimize to the tray instead of the task bar. 
ii) make sure you have 'minize on close' also set(make sure there is a checkmark in it) or bad things might happen
ii) hit OK

2) minimize bitcoin-classic

3) via the system tray icon, 'show' bitcoin-classic again.

what should happen:
alt-tab menu contains bitcoin-classic so you can alt-tab to other applications and back
what does happen:
alt-tab menu does not contain bitcoin-classic

what also should happen:
file settings help menu should be available when hitting alt key
what does happen:
hitting and holding alt key does nothing

what also should happen
file settings help menu should be available when you move the pointer to top of the screen
what does happen
moving pointer to the top of the screen when bitcoin-classic is current application does nothing.

This was a problem with bitcoin-core but they claim to have fixed it.
https://github.com/bitcoin/bitcoin/issues/1242
but after that other projects derived from bitcoin claim it isn't fixed
https://github.com/NeuCoin/neucoin/issues/20
this may be a unity bug 
https://bugs.launchpad.net/unity/+bug/1001498
and here is the reason why i report these 3 things as one bug -- according to this bug report minimizing causes more things than that to vanish...it really does seem like something is missing on the minimize/restore process that isn't just each individual issue.

this PR claims to resolve it
https://github.com/bitcoin/bitcoin/pull/3493
alas i do not have a bitcoin-core enviornment in unity yet to confirm.

**Comment by zander** [comment]
Initial thinking is that this may be a Qt issue which fails to work with unity. I don't have unity to test, it works for me on Qt5.8 and KDE.
Is Unity what you get by default in ubuntu?

> this PR claims to resolve it bitcoin#3493

The code from that PR is already present in the version you are running, notice that the PR is several years old.

ps. you might want to try classic from the PPA.
Nightly (master) https://launchpad.net/~bitcoinclassic/+archive/ubuntu/nightly
Stable https://launchpad.net/~bitcoinclassic/+archive/ubuntu/bitcoinclassic

**Comment by ghost** [comment]
Yeah unity is default in Ubuntu at least for now...it will no longer be come Ubuntu 17.10 I think though.
