### ISSUE TITLE
unknown location(0): fatal error: in "tx_validationcache_tests/tx_mempool_block_doublespend": memory access violation at address: 0x00000078: no mapping at fault address

### ISSUE THREAD

**Issue by supertux1** [bitcoinclassic/bitcoinclassic#275]
19:59:08 [DB] CDBEnv::MakeMock
    .275 Opened LevelDB successfully
    .275 Using obfuscation key for /tmp/test_bitcoin_1501358348_95792/regtest/blocks/index: 0000000000000000
    .275 Opened LevelDB successfully
    .275 Using obfuscation key for /tmp/test_bitcoin_1501358348_95792/regtest/chainstate: 0000000000000000
    .276 Initializing databases...
    .276 Pre-allocating up to position 0x1000000 in blk00000.dat
    .276 [Bench]   - Load block from disk: 0.00ms [0.00s]
    .276 [Bench]   - Connect total: 0.04ms [0.02s]
    .276 [Bench]   - Flush: 0.02ms [0.00s]
    .276 [Bench]   - Writing chainstate: 0.01ms [0.00s]
    .276 UpdateTip: new best=0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206  height=0  log2_work=1  tx=1  date=2011-02-02 23:16:42 progress=1.000000  cache=0.0MiB(0tx)
    .276 [Bench]   - Connect postprocess: 0.07ms [0.01s]
    .276 [Bench] - Connect block: 0.15ms [0.02s]
unknown location(0): fatal error: in "tx_validationcache_tests/tx_mempool_block_doublespend": memory access violation at address: 0x00000078: no mapping at fault address
test/txvalidationcache_tests.cpp(29): last checkpoint: "tx_mempool_block_doublespend" fixture entry.
    .279 [Coindb] Committing 0 changed transactions (out of 0) to coin database...
    .279 nFileVersion = 1030000
    .279 Keys: 0 plaintext, 0 encrypted, 0 w/ metadata, 0 total
    .280 [UAHF] Set UAHF: 3 
    .280 CreateNewBlock(): total size 1000 txs: 0 fees: 0 sigops 100
    .280 [UAHF] Check block found an UAHF chain block (based on timestamp) 1 95fa44471bf46b989dc82f3b51dfaf191a25394a0e1189158c09440c1c208c1e 

*** 1 failure is detected in the test module "Bitcoin Test Suite"
Database handles still open at environment close
Open database handle: unnamed/wallet.dat

**Comment by zander** [comment]
Thanks for reporting this.

Fixed by commit dc0e0f905835624182459a0e2e7c3900fe24e522
