### ISSUE TITLE
Stuck at Loading block index...

### ISSUE THREAD

**Issue by greenertux** [bitcoinclassic/bitcoinclassic#276]
I ran Bitcoin Classic bitcoind 1.3 (prebuilt binaries) on my Centos 7 machine yesterday and was stuck at the following error (message from bitcoin-cli getinfo):
error code: -28
error message:
Loading block index...

Today I tried the 1.3.1 binaries and have the same problem. I even compiled 1.3.1. myself, but it still does not work. My .bitcoin directory seems to be ok though, because I can still run 1.2.5 without any problems.

Is there anything I can do to debug this?

**Comment by zander** [comment]
Can you run your bitcoind with the -debug=1 flag, to generate more debugging info ?

Thanks!

The step of loading the block index is something that takes some time and does not have progress report. How much time did you give it?

**Comment by greenertux** [comment]
Thanks for your quick answer.

I let the 1.3.0 binaries run over night (about 9 hours), but it still did not complete (100% CPU all the time). With 1.2.5 it takes less than a minute for me.

This is my debug.log:

               .673 Bitcoin version v1.3.1.0-gc9d8572f1d7 (Sun, 30 Jul 2017 22:51:06 +0200)
               .673 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
               .675 [UAHF] UAHF state: 0 start time: 0 
               .696 Using BerkeleyDB version Berkeley DB 4.8.30: (May  5, 2014)
               .696 Startup time: 2017-07-31 08:00:03
               .696 Default data directory /root/.bitcoin
               .696 Using data directory /root/.bitcoin
               .696 Using config file /root/.bitcoin/bitcoin.conf
               .696 Using at most 50 connections (1024 file descriptors available)
               .696 Using 6 threads for script verification
               .697 scheduler thread start
               .697 [HTTP] Allowing HTTP connections from: 127.0.0.0/8 ::1/128 
               .697 [HTTP] Binding RPC on address ::1 port 8332
               .697 libevent: getaddrinfo: address family for nodename not supported
               .697 Binding RPC on address ::1 port 8332 failed.
               .697 [HTTP] Binding RPC on address 127.0.0.1 port 8332
               .697 [HTTP] Initialized HTTP server
               .697 HTTP: creating work queue of depth 16
               .697 [RPC] Starting RPC
               .698 [RPC] Starting HTTP RPC server
               .698 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
               .698 [HTTP] Registering HTTP handler for / (exactmatch 1)
               .698 [HTTP] Starting HTTP server
               .698 HTTP: starting 4 worker threads
               .698 Using wallet wallet.dat
               .698 [HTTP] Entering http event loop
               .698 init message: Verifying wallet...
               .698 CDBEnv::Open: LogDir=/root/.bitcoin/database ErrorFile=/root/.bitcoin/db.log
               .715 Bound to [::]:8333
               .715 Bound to 0.0.0.0:8333
               .715 Cache configuration:
               .715 * Using 2.0MiB for block index database
               .715 * Using 82.5MiB for chain state database
               .715 * Using 215.5MiB for in-memory UTXO set
               .715 init message: Loading block index...
               .715 Opening LevelDB in /root/.bitcoin/blocks/index
               .728 Opened LevelDB successfully
               .728 Using obfuscation key for /root/.bitcoin/blocks/index: 0000000000000000
               .728 Opening LevelDB in /root/.bitcoin/chainstate
               .739 Opened LevelDB successfully
               .739 Using obfuscation key for /root/.bitcoin/chainstate: 0000000000000000

**Comment by greenertux** [comment]
The output above is from my self compiled 1.3.1 with --disable-wallet set. Should I retry with the prebuilt binaries?

**Comment by zander** [comment]
Looks like no errors, are you sure its stuck? You cut it off at the loading phase, it may still be loading.

**Comment by greenertux** [comment]
The thing is it seems to be "stuck" at this point and take 100% CPU forever. I just let 1.3.1 self compiled bitcoind run for 8 minutes. It does not seem to me it will ever complete.

**Comment by zander** [comment]
your system is not by chance very low on memory or uses an old CPU?

It takes 5 - 15 seconds on other machines I tried it on.

**Comment by greenertux** [comment]
No, I have 12 GB of RAM.
As I said Bitcoin Classic 1.2.5 works perfectly and takes less than 1 minute to load. Usually when I start bitcoind and then run bitcoin-cli getinfo it is already at "Verifying blocks..."

Will try whether I can get 1.3.1 to run on my other machine now.

**Comment by zander** [comment]
since you said you would be able to compile it yourself, maybe you can try to check the method.
Its Blocks::DB::CacheAllBlockInfos  in src/BlocksDB.cpp at line 329

if you remove or comment out the line
`   appendHeader(iter->second)`
at line 371. That is practically speaking the only real difference between 1.2.5 and 1.3

**Comment by greenertux** [comment]
I just tried on my laptop (Ubuntu). The issue is the same (also coming from self-compiled 1.2.5)
Uncommenting line 371 fixes the issue. Will try on the server as well but I hope it will also work there.

**Comment by zander** [comment]
Cool, thanks for trying :)

That change won't have any negative effects on your node, so don't worry running that. I'll check if I can find a faster way.

**Comment by zander** [comment]
FIxed for now in 056532dfd2878bc8ab52d984ea2c6e8113af55ac

**Comment by Jeans5** [comment]
Hey, my problem is very similar to the one described above. Could you explain how it is fixed? First I get error message of -28, but also this one:

error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

Thx!
