### ISSUE TITLE
Remove libsecp from validation.

### ISSUE THREAD

**Issue by circeng** [bitcoinclassic/bitcoinclassic#28]
Bitcoin Core recently added dangerous home-brew cryptographic code developed by BlockStream to the heart of the Bitcoin protocol without any public consensus. This change has been highly controversial because the claimed performance is not possible without dangerous, speculative, and unreviewed algorithms which may contain serious flaws or intentional back-doors.

The claimed performance increase is both dubious and unimportant. Using the _standard_ cryptographic software that 0.11 used even low performing hardware can handle blocks of hundreds of megabytes in size, so there is no need to switch off of widely reviewed software which has been used by millions of people for years except to entrench BlockStream control of the Bitcoin protocol.

**Comment by jtoomim** [comment]
Disagree strongly. Libsecp256k1 is one of the purest technical improvements that has been made in Bitcoin in ages.

**Comment by jtoomim** [comment]
In the absence of a consider.it vote supporting this issue, I am going to close it. If you can show me a vote in support of this being an issue, I will reopen it.

Note: This bears resemblance to a trolling attempt, so I will not be wasting time on it. I recommend that other users evaluate submissions from @circeng and from @cointrader (https://github.com/bitcoinclassic/bitcoinclassic/pull/29#issuecomment-172390698) with caution.

**Comment by ciphera** [comment]
This should probably be considered if your hard fork goes through and the major developers of this lib (maxwell and wuille) quits Bitcoin. Leaving it unmaintained would be insecure, and a better option would be to run OpenSSL again. Unless you find someone else who is qualified to maintain it of course.

**Comment by murchandamus** [comment]
Libsecp256k1 has an extensive test coverage, much greater than OpenSSL’s. I wouldn’t expect any issues with its maintenance. To quote [andytoshi’s review](https://bitcointalk.org/index.php?topic=937058.msg10278072#msg10278072):

> libsecp256k1's code is simpler and cleaner; it is designed specifically for ECDSA, so it is a much much smaller codebase (less room for error and reviewers can look more closely at the specific ECDSA code); its test coverage is more thorough. The code is also written in a modular way with the explicit goal of being easy to analyze.
