### ISSUE TITLE
Redo the UAHF-rollback code with block-height and uint256.

### ISSUE THREAD

**Issue by gurnec** [bitcoinclassic/bitcoinclassic#282]
If I understand correctly (and I may not), [these lines](https://github.com/bitcoinclassic/bitcoinclassic/blob/1c839b300fc90d796c4c7619630ae1333a5bcc34/src/main.cpp#L3619-L3620) find the last block whose MTP is <= 1501590000 (block 478557), then two lines down (3622) adds one, which is the last shared block (478558) between the two chains (the "pre-fork block"). The *following* block should be the fork block / the first block >1MB in the UAHF (478559).

However it looks like [this code](https://github.com/bitcoinclassic/bitcoinclassic/blob/1c839b300fc90d796c4c7619630ae1333a5bcc34/src/main.cpp#L3624-L3632) is checking the pre-fork block's (478558) size. Shouldn't [line 3622](https://github.com/bitcoinclassic/bitcoinclassic/blob/1c839b300fc90d796c4c7619630ae1333a5bcc34/src/main.cpp#L3622) read `forkHeight = blockIndex->nHeight + 2;`?

Also relevant, when I started Bitcoin Classic 1.3.3 (in UAHF/BCC mode) based on a blocks directory created by Bitcoin ABC, I received this in the debug.log:
```
               .857 [UAHF] Set UAHF: 2 
               .857 [UAHF] Detected your chain was not UAHF, will need to rollback to the fork-block! 
               .857 [UAHF]  Fork-block is at: 478558 
```

FYI I believe that [this while condition](https://github.com/bitcoinclassic/bitcoinclassic/blob/1c839b300fc90d796c4c7619630ae1333a5bcc34/src/main.cpp#L3659) is correct - it rolls back 478559, but not 478558, however [this](https://github.com/bitcoinclassic/bitcoinclassic/blob/1c839b300fc90d796c4c7619630ae1333a5bcc34/src/main.cpp#L3654) would have a cosmetic bug if the first bug were fixed - it would log that one too few blocks needed to be rolled back.

**Comment by zander** [comment]
Now the fork is 'done' we no longer care as much about the MTP, what we care about is the block number and the blockid (the hash).

As such the code linked to can be made much simpler by just hard-coding the actual numbers.

I'd love it if someone managed to write the code for this. I'll do the testing if you just send me the code.
