### ISSUE TITLE
Misbehaving: XX.XX.XX.XX:8333, id:16 (0 -> 100) BAN THRESHOLD EXCEEDED

### ISSUE THREAD

**Issue by soeren-b-c** [bitcoinclassic/bitcoinclassic#283]
On an install of v1.3.3uahf (64-bit) on top of another bitcoin client (with the intent to share the blockchain data dir) the Classic node seems stuck, and the log shows a lot of
"Misbehaving: " - "(0 -> 100) BAN THRESHOLD EXCEEDED"

Some of the nodes that are supposed to be misbehaving I know for a fact are on the Cash-chain, so that is not the problem.

Let me know if you need further info.

**Comment by mmouse-** [comment]
Can confirm that. 
I have v1.3.3 compiled from source, set
`uahfstarttime=1501590000`
`flexiblehandshake=true`
in bitcoin.conf. But it still bans every BUCash (Bitcoin Unlimited) node even if it's on the correct chain.  

While Classic's behaviour might be correct technically, it isn't helpful at all.

**Comment by zander** [comment]
would you happen to have am unconfirmed transaction in your wallet?

**Comment by soeren-b-c** [comment]
Yes, it would seem so.

**Comment by zander** [comment]
The 1.3.4 release has several bugfixes that would make this better.

If you can, I suggest removing your peers.dat before restarting.
