### ISSUE TITLE
Bitcoin Classic - Not connecting to the network

### ISSUE THREAD

**Issue by ScalaAr** [bitcoinclassic/bitcoinclassic#286]
I've just downloaded and installed Bitcoin Classic wallet on my PC (Windows 10, 64 bits Professional).

Bitcoin core is working as expected.

Bitcoin Classic shows a "No block source available..."  message, even is has between 3-4 active connenctions and it is stuck on 479868 blocks.

Any idea of how to solve this will be greatly appreciated

**Comment by zander** [comment]
Typically waiting a big longer makes the node find connections.

Alternatively check a new version just released 1.3.4

If you can, delete the peers.dat file before you start the new one.
