### ISSUE TITLE
Can't build from source with --disable-wallet (UAHF)

### ISSUE THREAD

**Issue by protonn** [bitcoinclassic/bitcoinclassic#289]
https://github.com/bitcoinclassic/bitcoinclassic/releases/tag/v1.3.4uahf

./configure --disable-tests --without-gui --disable-wallet

  CXX      support/libbitcoin_util_a-pagelocker.o
  CXX      libbitcoin_util_a-allowed_args.o
In file included from ./wallet/walletdb.h:10:0,
                 from wallet/wallet.h:17,
                 from allowed_args.cpp:20:
./wallet/db.h:21:20: fatal error: db_cxx.h: No such file or directory
compilation terminated.
Makefile:4208: recipe for target 'libbitcoin_util_a-allowed_args.o' failed
make[2]: *** [libbitcoin_util_a-allowed_args.o] Error 1
make[2]: Leaving directory '/xxx/xxx/bitcoinclassic/src'
Makefile:7049: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/xxx/xxx/bitcoinclassic/src'
Makefile:600: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

No problems using these configure flags with Bitcoin ABC or any other coin, so I don't think it's a problem with my system or configuration.

**Comment by zander** [comment]
Thanks for the report, the issue is specifically if you don't have the berkley db installed, which is why I didn't notice it before.
