### ISSUE TITLE
Replace C-includes with C++ includes

### ISSUE THREAD

**Issue by zander** [bitcoinclassic/bitcoinclassic#291]
Because C++ is build on top of C it is perfectly legal to mix the two.

But as we want to move from a C codebase to something more object oriented, lets start with all simple things.

We have various places where c-library includes are used. These are files like `<stdint.h>`, and we want to replace that with the C++  versions, in this case `<cstdint>`

Similarly for files like cstring, cstdint, cstdlib, cstdio, casserts, cmath, climits, cerrno, cstdarg
etc.

BE CAREFUL to not modify any file in the 3rd party library directories src/leveldb, src/univalue and src/secp256k1

**Comment by gubatron** [comment]
almost done with this

**Comment by gubatron** [comment]
https://github.com/bitcoinclassic/bitcoinclassic/pull/292
