### ISSUE TITLE
BCH Wallet balance shows BTC Wallet balance

### ISSUE THREAD

**Issue by ScalaAr** [bitcoinclassic/bitcoinclassic#293]
Hi, 

I need help with the following issue:

On August 10th (aprox) I move some BTC I have stored in my Bitcoin Core wallet to a new account.

I then install the BCH Bitcon Classic wallet on a new computer and import the BTC wallet.

It start syncing the blockchain locally from scratch (as expected), but It always shown a 0 balance because it includes the transfer I made after the fork witch I was expecting to be "deleted" or "invalidated" after the blockchain sync ended.

When it finally synced my BCH shows a 0 balance and a transaction that is not confirmed even it was made several days ago.

How can I correct this? It will eventually solve by itself? 

Any help would be greatly appreciated

**Comment by zander** [comment]
I don't know what you did as very little of your description can be applied to actual Bitcoin Classic usage, so I think you got confused with some other software.

I suggest you install the "Bitcoin Classic UAHF" client and use that.

https://github.com/bitcoinclassic/bitcoinclassic/releases/tag/v1.3.4uahf

**Comment by ScalaAr** [comment]
zender,
I'am indeed using Bitcoin Classic UAHF. There is the issue, as the transaction placed on BTC walled AFTER the fork is showing in the BCH Wallet!

I'm showing a print screen of the BCH wallet, 

In the screen capture ALL the transactions were made on the BCT wallet and the last withdraw made on Aug-13 should not affect the BCH balance... Is this correct?

![2017_08_19_13_06_41_redactar_administrador_de_tareas_de_windows_occidental_windows_1252_](https://user-images.githubusercontent.com/30990467/29488393-80d13fde-84e0-11e7-80d2-90346103a6f6.png)

**Comment by zander** [comment]
The way you imported the wallet may have lead to this result,

it would likely be solved by restarting with the `-rescan=true` argument appended. This takes a while, but your BTC transaction should then be removed.
