### ISSUE TITLE
BCH Wallet balance shows BTC Wallet balance

### ISSUE THREAD

**Issue by ScalaAr** [bitcoinclassic/bitcoinclassic#294]
zender,

This is a replay of the closed #Issue #293 (https://github.com/bitcoinclassic/bitcoinclassic/issues/293)

I'am indeed using Bitcoin Classic UAHF (v1.3.4uahf). There is the issue, as the transaction placed on BTC walled AFTER the fork is showing in the BCH Wallet!

I'm showing a print screen of the BCH wallet,

In the screen capture ALL the transactions were made on the BCT wallet and the last withdraw made on Aug-13 should not affect the BCH balance... Is this correct?

Any idea or help will be *REALLY* appreciated

![2017_08_19_13_06_41_redactar_administrador_de_tareas_de_windows_occidental_windows_1252_](https://user-images.githubusercontent.com/30990467/29490330-4fc4d16a-850f-11e7-916e-fb9c1db8cee7.png)

**Comment by zander** [comment]
Duplicate. Closing.
