### ISSUE TITLE
UAHF 1.3.5 Misbehaving: A.B.C.D:8333, id:193 (0 -> 100) BAN THRESHOLD EXCEEDED

### ISSUE THREAD

**Issue by cross** [bitcoinclassic/bitcoinclassic#298]
I looked at Issue #283 but it sounded like that was improved since 1.3.3.  I'm running 1.3.5, I tried removing peers.dat, but.  I may have done something else wrong.

I have a blockchain I copied from a Bitcoin Core client.  In the end, I ended up deleting most everything except the blockchain that I'd copied into the BitcoinClassic-UAHF directory.  I also deleted the ref and blk files newer than July 28, 2017, as there was a larger problem before I did.

When I start up the 1.3.5 client (Mac), it claims to be using a bitcoin.conf in the BitcoinClassic-UAHF directory, but no such file exists.  The LevelDB in BitcoinClassic-UAHF/blocks/index opens successfully, as does the LevelDB in BitcoinClassic-UAHF/chainstate.  Block index says last block file = 0, but I assumed it would reindex after I'd deleted the newer blocks and index files.  UPNP seems not to work most often, but I manually configured the UPNP to work around that, and see port 8333 forwarded at my IGD.

But, after that, I just see a chain of connection refused errors, that I assume are normal, and a number of the aforementioned error "Misbehaving [...] 0 -> 100) BAN THRESHOLD EXCEEDED".

Is taking a blockchain that was previously used by Bitcoin Core okay?  Is there something I missed for the UAHF client to run properly?

**Comment by rossigee** [comment]
On 27/08/2560 21:31, Chris Ross wrote:
> But, after that, I just see a chain of connection refused errors, that I
> assume are normal, and a number of the aforementioned error "Misbehaving
> [...] 0 -> 100) BAN THRESHOLD EXCEEDED".
> 

I was having a similar problem recently. My copy of the chain had
already moved on along the Core path after the fork, and I then started
running it with UAHF options set. I believe this error is saying that
the new block that the peer is sending doesn't seem to follow on
(mathematically) from the previous block I have on my local chain for
that block number because the last block on my local chain came from the
Core path (iyswim!).

> Is taking a blockchain that was previously used by Bitcoin Core okay? Is
> there something I missed for the UAHF client to run properly?
> 

I found that by invalidating block 485885 and restarting bitcoind, it
would 'rewind' itself (discarding blocks one-by-one until it gets to the
fork block), and would then continue along the correct path.

I used the following command to invalidate the block:

bitcoin-cli invalidateblock
00000000000000000019f112ec0a9982926f1258cdcc558dd7c3b7e5dc7fa148

I got this from this Reddit post, which was pointed out by tomz on Slack.

https://www.reddit.com/r/btc/comments/6uukri/want_to_upgrade_your_full_node_from_bcore_chain/dlvlkr5/

Hope this helps.

--
Ross

**Comment by cross** [comment]
Great.  Thanks for that advice.  I look forward to trying that, but I need bitcoin-cli it seems.  I'm on a Mac.  Google'ing around, it looks like the Bitcoin Core folks distribute a .tar.gz file, separate from the .dmg file, for the mac that includes bitcoind and bitcoin-cli.  I assume I could use that against the "to be the new UAHF datadir for Bitcoin Classic" without issue, but I'm not sure.

Is there a bitcoin classic distribution of the non-UI tools for Mac?

**Comment by cross** [comment]
Hmm.  Okay, I found the console within the UI, and issued the command.  I didn't check before to see what it thought the blockchain looked like, via report from the app, but after I issued the command the debug log shows:

`2017-08-28 18:13:26 InvalidChainFound: invalid block=00000000000000000019f112ec0a9982926f1258cdcc558dd7c3b7e5dc7fa148  height=478559  log2_work=86.861505  date=2017-08-01 13:23:00`
`               .725 InvalidChainFound:  current best=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f  height=0  log2_work=32.000022  date=2009-01-03 18:15:05
`

And, the debug window info shows the last block as 0, Jan 2009.  Maybe this is because I deleted my index directory?  Either way, I'm still seeing the BAN THRESHOLD EXCEEDED errors, and no progress.

Maybe I should restart with the whole blockchain from Bitcoin Core, with only the invalidateblock above, rather than the mucking I was doing with files behind the scenes.  :-/

Thanks.  Happy to hear any other ideas.

**Comment by zander** [comment]
The simplest top-level description to split your BTC and your BCC I gave in this reddit post;

https://www.reddit.com/r/btc/comments/6uukri/want_to_upgrade_your_full_node_from_bcore_chain/

maybe you can get some info from that.

The simple fact that nodes are being banned is not very relevant, what is relevant is knowing how many actually stay connected. If you have the latest version this should be at least 7 connections.

**Comment by zander** [comment]
You can find the tar.gz here; https://github.com/bitcoinclassic/bitcoinclassic/releases/tag/v1.3.5uahf

It think you would need to do a reindex. Start your bitcoind or bitcoin-qt with `-reindex=true` and check your logs.

For the record; doing a plain first download should also work just fine, it did two weeks ago when I did so.

**Comment by cross** [comment]
> The simplest top-level description to split your BTC and your BCC I gave in this reddit post;[...] maybe you can get some info from that.

That's interesting, especially because it talks about using both with the same blocks.  I'd like to talk to you more about how to make that work.  On the Mac, at least, I know it won't work quite the way you describe in that post, but.

> The simple fact that nodes are being banned is not very relevant, what is relevant is knowing how many actually stay connected. If you have the latest version this should be at least 7 connections.

It was definitely making some connections, some blocked some not.  I don't know if it got up to 7.  But, it seemed to be making no progress.  It wasn't noting receiving any blocks, and as far as I could tell from the debug.log it wasn't doing anything other than listening to/for connections, and sometimes banning peers.

> It think you would need to do a reindex. Start your bitcoind or bitcoin-qt with -reindex=true and check your logs.

Thanks!  I re-updated to a full copy of the Bitcoin Core directory, blocks DBs and all, and did that.  It seems to be proceeding with that, although it's been a few hours and it's still in 2012.  That will take a while.  ;-)  Hopefully that will be good after that...  Do you think I will still have to invalidate the block as @rossigee suggested above, or will the reindex take care of all of that "figuring out to ignore the newer blocks" after it's done?

**Comment by cross** [comment]
So, the reindex run got cut off, and when resuming the application without -reindex=true, it seemed to be very confused.  So, I stopped it and started it again with -reindex=true .  It seems to be taking an unduely long time, but.  Validations are being written in debug.log, currently looking like:

`2017-08-30 03:29:08 [Validation] new best=000000000000003c5be833cc03ef979b4dfa21895fc8e03dc8d2287b99243079 height=255952  log2_work=71.6437  tx=23215047  date=2013-09-03 19:34:56  progress=0.0568974  cache=89.0MiB(108380tx)`
`                   .234 [502]   6: For conf success > 0.95 need FeeRate >:   4.2612e+05 from buckets   445792 -   445792  Cur Bucket stats  93.64%   12647.2/(13506.3+0 mempool)`

While each **Validation** line has a new `height=` (and `date` and `progress`), I'm seeing that second line after most Validation lines, and it's always the same.  What does that second line above mean?  Why it is talking about conf success, FeeRate, buckets 445792-445792, and 93.64% bucket stats?  That seems totally unrelated to the validation that's going on, but it keeps saying the same thing over and over, so I'm questioning what it is/means...

I'll end up closing this issue I think, as I think I'm past the original problems details, but the same issue exists, so I'll forum here while waiting to see if the problem is resolved.  All help appreciated.

**Comment by zander** [comment]
The second part, the one with [502], seems to be a part of the major logging upgrade we are going through. I'd say its mostly debugging info meant only for developers. You can safely ignore those lines.

The reusing of blocks should work on all platforms, I added some code for Classic to just try multiple directories to find an old block. Nothing platform specific about that.

I'm happy to hear things are progressing, and you should be able to get fully synced as long as you find some Classic/ABC or BUCash nodes to connect to.

**Comment by cross** [comment]
Okay, thanks.  That was the line I was worried about, as it's occurring repeatedly and didn't make sense [to me].  Happy to ignore it.

How can I tell classic to try multiple directories for blocks?  Specifically, a directory to find an old block, but hopefully not update?  I notice while doing the reindex that it's recreating all the rev files, so I assume those can't safely be reused between Core and Classic-UAHF?  At least, it will change them.

The Mac has the same bundle-id for the app for both Core and Classic, so they share a preferences file, where their datadir spec is retained.  I can manually run the underlying binary with arguments, as I've been doing to point them at different data dirs, so if I can tell Classic UAHF something to look in a secondary place, I can rig that up.

I could hard-link the blk* files to each other, leaving them in different directories.  But, I want to get it all working with full copies of the chain first, just to make sure not to mess anything up.  :-)

**Comment by zander** [comment]
the Classic client introduced a new config option that it stores in the bitcoin.conf for the BitcoinCash datadir. That new option looks something like this `blockdatadir=/home/tomz/.bitcoin`.
This adds the idea that Bitcoin classic will fall back to that directory to find block files it doesn't find locally.

You can have any number of blockdatadir entries. May be useful to store some blocks on an external drive or even a network drive.

> The Mac has the same bundle-id for the app for both Core and Classic, so they share a preferences file, where their datadir spec is retained. 

The UAHF version should ignore the datadir there and instead go to the BitcoinCash directory. This is when you either download the UAHF version, or you manually start it with `-uahf=true`. Would appreciate if you can tell me if that fails to work on MacOS.

Doing a re-index while the `blockdatadir` is set is untested, I expect the revert files to be created in the 'local' dir.
