### ISSUE TITLE
1.3.5uahf Mac OS, 'No block source available' after migration

### ISSUE THREAD

**Issue by jkdelauney** [bitcoinclassic/bitcoinclassic#299]
Installed 1.3.5uahf Mac OS prebuilt and ran it. Blocks were collecting as expected.

Needed to restart the machine, so existed Bitcoin Classic. No apparent issues stopping the application. After rebooting and starting the application received a message about the file migration. Once startup was completed the 'No block source available' message displayed on the status line in spite of multiple peers being connected. Left application running for the day (about 10 hours) but returned to find the same message and no progress having been made in the block collection.

Tried fresh install, exited and restarted the application with identical results.

**Comment by zander** [comment]
In the Bitcoin network we still use the same connection info as the legacy chain, as such we connect to them and in many cases we notice shortly after that this won't work and ban them for 24 hours.

In my experience it may take between 5 and 15 minutes to get at least one connection that we can use to sync. The notice you talk about won't go away until we get 3 or 4 connections, though. So thats a little confusing.

A couple of things you can try;

Open your dir  "Library/Application Support/BitcoinCash" and before starting Classic remove your peers.dat.  This has the result to check the DNS and those will give you nice peers to connect to.

If that doesn't work, go to https://bitnodes.21.co/nodes/?q=NODE_CASH and check a node there that is close to you. Copy its address (the one in the form of `123.12.12.123:8333`)
Then go to the `Debug Window` which you can open from the `Help` menu.

In the `Console` tab paste the following in the command line at the bottom;
    `addnode ADDRESS onetry`
replacing the ADDRESS with the one you found on the bitnodes.21.co site.
Press enter to submit.

You can repeat this with many addresses as it takes.

**Comment by jkdelauney** [comment]
Since posting this I attempted running with the reindex switch as I had come across some old references to a corrupted index could result in that message. I am seeing that the client is collecting new data, though as I left the machine unattended I'm unaware at what point things started working.

If it would be useful I can isolate this install and try again to see if forcing a node produces a faster resolution. Though I did try deleting the peers.dat file initially as I'd come across that elsewhere as a possible solution but to no avail.

If this is just a matter of waiting for usable connections and not just any connections it might be useful to either introduce additional/different wording to the status message, or some verbiage to the migration notification at restart (which erroneously states first run) to advise the user of this issue.

**Comment by zander** [comment]
I fixed several issues in the 1.3.7 release, there is a very good chance that this solves the issue of a node not downloading new data.

I'll close the bug as I assume this solves it.
If you still have problems with the 137 release, comment here to reopen it.

**Comment by fm444fm** [comment]
It is still a problem. See: https://github.com/bitcoinclassic/bitcoinclassic/issues/313

**Comment by cross** [comment]
Yup, seeing this in 1.3.7uahf, as noted in #313.  Thanks.

**Comment by cross** [comment]
@zander Commenting here doesn't seem to have reopened this.  Can you reopen it please?
