### ISSUE TITLE
Bitcoin Classic cannot use an existing Cash blockchain

### ISSUE THREAD

**Issue by OverlordQ** [bitcoinclassic/bitcoinclassic#300]
There's nothing in the code that ever sets `uahfChainState` to active *except* for the call to `setUahfForkBlock` which is only called by `ConnectBlock` which will never get called if you're already hundreds of blocks past the fork.

**Comment by OverlordQ** [comment]
And this was my hacky solution to get it to accept blocks again:
https://github.com/OverlordQ/bitcoinclassic/commit/3fe1ee5ca291cf6d803a3d42aa34787dfcd54e50

**Comment by zander** [comment]
> There's nothing in the code that ever sets uahfChainState to active

The call is here;
https://github.com/bitcoinclassic/bitcoinclassic/blob/master/src/BlocksDB.cpp#L508

which is called on startup during blocks-index parsing;
https://github.com/bitcoinclassic/bitcoinclassic/blob/master/src/BlocksDB.cpp#L384

> And this was my hacky solution to get it to accept blocks again:
> OverlordQ/bitcoinclassic@3fe1ee5

I see.

I think the solution would be more stable with some refactoring that removes the usage of the BlocksDB here.

I'll propose something soon.

**Comment by zander** [comment]
@OverlordQ I pushed an update to classic, would you be able to pull and try if that makes things work for you?

**Comment by zander** [comment]
Fixed in v1.3.6
