### ISSUE TITLE
Shares Mac bundle-id with Core Bitcoin-Qt app

### ISSUE THREAD

**Issue by cross** [bitcoinclassic/bitcoinclassic#301]
I presume that something in the Mac build process could be changed so that there is a different bundle id.  Both the Bitcoin Core 0.14.2 and Bitcoin Classic 1.3.5 share the same bundle identifier (org.bitcoinfoundation.Bitcoin-Qt)  (On my system, they're actually both using the org.bitcoin.Bitcoin-Qt.plist preference file on my system so something must be finding that as an old name)

At any rate, I think you should compile the Mac Bitcoin Classic with a different bundle identifier.  This would, I believe, allow it to maintain different preferences (including but not limited to specification of datadir, which is where I was wanting the difference) per application.

<pre>
cross@machost: mdls -name kMDItemCFBundleIdentifier /Applications/Bitcoin\ Classic-UAHF.app   
kMDItemCFBundleIdentifier = "org.bitcoinfoundation.Bitcoin-Qt"
cross@machost: mdls -name kMDItemCFBundleIdentifier /Applications/Bitcoin-Qt.app            
kMDItemCFBundleIdentifier = "org.bitcoinfoundation.Bitcoin-Qt"
</pre>

**Comment by zander** [comment]
Fixed, thanks for the report!
