### ISSUE TITLE
The EDA is a serious issue

### ISSUE THREAD

**Issue by ghost** [bitcoinclassic/bitcoinclassic#312]
It's insane to mine 30 blocks/hour. If we don't fix the EDA algorithm this crazy oscillation will never stop. When these mining pools adopt auto switch mining（Bitcoin.com already did）, the oscillation will occurs even more frequently( 1% more profit will make the hashpower switch). We can't beg some kind miners to keep mining with less profit to stop the EDA lock in. It is not a long-term mechanism which backed by game theory and economic incentives. 

'As such, if the market perceives the BCC chain as better, the fluxuations 
will stop as the majority of the hashpower starts moving to it. Permanently.'---Tom Zander

Tom, I'm really worried about your thinking. Why you so sure it's so obvious that market should notice BCC chain is better. Market is greedy, they only care about profit and price. The inflation caused by EDA will keep BCC’s price down and slow the adoption. Hashpower won't move to BCC permanently, unless BTC dies. But if we don't fix the EDA, BCC may die first（the reward halving will arrive much quicker than BTC，which also means hashpower halving）.

As a user，I'd like to accept BCC in my store，but waiting 6 hours for a single confirm？You gotta be kidding me.

Sorry about my broken English，but I think I made my point.

**Comment by zander** [comment]
It may be useful to note that I largely agree with you.

I noticed this issue before we forked off, and I proposed a solution which has been ignored by the rest of the community; https://github.com/Bitcoin-UAHF/spec/pull/15

I even proposed a solution for this on the mailinglist as well.

Unfortunately the reality is that we need a hard fork to fix this. Nothing I say or do will change that. On top of that it is a change that 100% of the wallets, miners and users need to follow.
