### ISSUE TITLE
UAHF not downloading blocks

### ISSUE THREAD

**Issue by cross** [bitcoinclassic/bitcoinclassic#313]
I was having misc problems with 1.3.4/1.3.5uahf (issue #298 ), ended up doing a full -reindex.  That took a very long time.  

But, it eventually finished, stopping at at hard fork.  I then exited that run, and ran normally.  It maintains reporting "No block source available".  It seem to have 5-8 connections at a time, many to bitcoinABC or others that have the higher block count that I believe is indicative of a bitcoin-cash blockchain.  But, the debug window continues to note the Block chain I have has 478558 blocks in it, last block time Tue Aug 1.  I left it run overnight.

I updated to 1.3.7uahf this morning, to see if it changed anything, but it has not so far.  I've been running for more than 6 hours now, no new blocks.

What else can I try?  Thanks.

**Comment by cross** [comment]
[uahf-debug.log](https://github.com/bitcoinclassic/bitcoinclassic/files/1327326/uahf-debug.log)

**Comment by fm444fm** [comment]
I have exactly the same problem. Re-downloaded entire blockchain while I was on 1.3.6uahf and it didn't help, still stuck at 7weeks (time of the hard fork). Then installed 1.3.7uahf, same thing. Then re-indexed, took a really long time, and still it is blocked at 478558. Also tried, through the gui console, to add manually some CASH nodes... to no avail. What to do next? Thank you

**Comment by cross** [comment]
There's no response on either this issue, or #299 (which remains closed).  Help?

**Comment by zander** [comment]
Hi all,

sorry about the problems. As you can imagine, I have not seen these issues on a machine I have access to. I need a little help figuring out what is going on.

Please install 1.3.7
Then remove your debug.log
Then start Classic with `-debug` and keep it running for a couple of minutes.

After shutting down Classic, please attach the resulting debug log file for me.

Thanks!

**Comment by archon5880** [comment]
17:20:14 [Net] parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1 
    .351 [UAHF] UAHF state: 1 start time: 1501590000 
17:20:17 [Wallet] Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010) 
    .817 [Bitcoin] Startup time: "2017-10-01 17:20:17" 
    .817 [Bitcoin] Using data directory "C:\Users\User.user-PC\AppData\Roaming\BitcoinCash" 
    .817 [Bitcoin] Using config file "C:\Users\User.user-PC\AppData\Roaming\BitcoinCash\bitcoin.conf" 
    .821 [Wallet] Using wallet "wallet.dat" 
    .821 [Bitcoin] init message: "Verifying wallet..." 
    .835 [Bitcoin] init message: "Loading block index..." 
    .835 [DB] Opening LevelDB in "C:\Users\User.user-PC\AppData\Roaming\BitcoinCash\blocks\index" 
    .989 [DB] Opening LevelDB in "C:\Users\User.user-PC\AppData\Roaming\BitcoinCash\chainstate" 
17:20:23 [Bitcoin] LoadBlockIndexDB: hashBestChain: 0000000000000000011865af4122fe3b144e2cbeea86142e8ff2fb4107352d43 height: 478558 date: "2017-08-01 13:16:14" progress: 0.983142 
    .631 [Bitcoin] init message: "Verifying blocks..." 
17:20:27 [Bitcoin] init message: "Loading wallet..." 
    .250 [Bitcoin] init message: "Activating best chain..." 
    .254 [Bitcoin] init message: "Loading addresses..." 
    .410 [Bitcoin] init message: "Done loading" 
17:20:28 [Net] receive version message: 158.69.253.36:8333 "/Satoshi:0.14.2/" version: 70015 blocks: 487831 id: 1 
17:20:34 [Net] receive version message: 35.157.227.145:8333 "/Bitcoin ABC:0.14.6(EB8.0)/" version: 70015 blocks: 491220 id: 2 
17:20:35 [Net] receive version message: 5.9.144.83:8333 "/Bitcoin ABC:0.15.0(EB8.0)/" version: 70015 blocks: 491220 id: 3 
17:20:36 [Net] receive version message: 52.14.80.90:8333 "/Satoshi:0.14.1/" version: 70015 blocks: 487831 id: 4 
17:20:47 [Net] receive version message: 80.127.136.50:8333 "/Satoshi:0.14.2/" version: 70015 blocks: 487831 id: 5 
17:20:48 [Net] receive version message: 104.198.84.14:8333 "/Satoshi:0.14.0/" version: 70015 blocks: 487831 id: 6 
17:20:54 [Net] receive version message: 116.62.173.127:8333 "/Satoshi:0.14.2/" version: 70015 blocks: 487831 id: 7 
17:21:01 [Net] receive version message: 116.125.120.26:8333 "/Bitcoin XT:0.11.0/" version: 70010 blocks: 487831 id: 8 
17:21:02 [Net] receive version message: 168.235.85.138:8333 "/Satoshi:0.14.1(UASF-SegWit-BIP148)/UASF-Segwit:0.3(BIP148)/" version: 70015 blocks: 487831 id: 9 
17:21:13 [Net] receive version message: 88.99.184.81:8333 "/Satoshi:0.14.1/" version: 70015 blocks: 487831 id: 10 
    .901 [Net] receive version message: 23.253.151.73:8333 "/Satoshi:0.12.1/" version: 70012 blocks: 487831 id: 11 
17:21:25 [Net] receive version message: 47.89.179.181:8333 "/Satoshi:0.14.0/" version: 70015 blocks: 487831 id: 12 
17:21:47 [Net] receive version message: 13.55.200.177:8333 "/Bitcoin ABC:0.14.6(EB8.0)/" version: 70015 blocks: 491221 id: 13 
17:22:09 [Net] receive version message: 62.210.93.229:8333 "/Satoshi:0.14.2/" version: 70015 blocks: 487831 id: 14 
17:22:27 [Net] receive version message: 120.24.67.56:8333 "/Satoshi:0.14.0/" version: 70015 blocks: 487831 id: 15 
17:22:37 [Net] receive version message: 5.9.19.109:8333 "/Bitcoin ABC:0.15.0(EB8.0)/" version: 70015 blocks: 491222 id: 16 
17:22:43 [Net] receive version message: 104.199.238.17:8333 "/Satoshi:0.14.1/" version: 70015 blocks: 487831 id: 17 
17:22:54 [Net] receive version message: 123.57.190.221:8333 "/Satoshi:0.14.0/" version: 70015 blocks: 487831 id: 18 
17:23:00 [Net] receive version message: 82.1.62.112:8333 "/Satushi:0.13.69(UASF-SegWit-BIP148)/" version: 70015 blocks: 487831 id: 19 
17:23:11 [Net] receive version message: 88.99.191.228:8333 "/Satoshi:0.14.1/" version: 70015 blocks: 487831 id: 20 
17:23:44 [Net] receive version message: 83.137.145.139:8333 "/Bitcoin XBC:0.14.6(EB8.0)/" version: 70015 blocks: 491222 id: 21 
17:23:45 [Net] receive version message: 5.56.40.1:8333 "/BitcoinUnlimited:1.0.2(EB16; AD12)/" version: 80002 blocks: 487831 id: 22 
17:24:08 [Net] receive version message: 47.88.62.100:8333 "/Bitcoin ABC:0.15.0(EB8.0)/" version: 70015 blocks: 491223 id: 23 
17:24:13 [Net] receive version message: 154.66.207.126:8333 "/Satoshi:0.14.2/" version: 70015 blocks: 487831 id: 24 
17:24:42 [Net] receive version message: 119.23.161.187:8333 "/Bitcoin ABC:0.15.0(EB8.0)/" version: 70015 blocks: 491223 id: 25 
17:24:53 [Net] receive version message: 185.154.156.55:8333 "/Satoshi:0.14.1/" version: 70015 blocks: 487831 id: 26 
17:24:54 [Net] receive version message: 94.211.248.93:8333 "/Satoshi:0.14.2/" version: 70015 blocks: 487831 id: 27 
17:25:00 [Net] receive version message: 178.63.3.196:8333 "/Satoshi:0.11.1/" version: 70002 blocks: 487831 id: 28 
17:25:05 [Net] receive version message: 27.133.128.7:8333 "/Satoshi:0.12.1(bitcore)/" version: 70012 blocks: 487831 id: 29 
17:25:11 [Net] receive version message: 82.69.201.108:8333 "/Bitcoin ABC:0.14.6(EB8.0)/" version: 70015 blocks: 491225 id: 30 
17:25:17 [Net] receive version message: 118.190.97.213:8333 "/Satoshi:1.14.4(2x)/" version: 70015 blocks: 487831 id: 31 
17:25:23 [Net] receive version message: 163.172.23.15:8333 "/Satoshi:0.13.2/" version: 70015 blocks: 487831 id: 32 
17:25:29 [Net] receive version message: 134.17.26.116:8333 "/Satoshi:0.14.2/" version: 70015 blocks: 487831 id: 33 
17:25:34 [Net] receive version message: 72.83.230.244:8333 "/Satoshi:0.14.2/" version: 70015 blocks: 487831 id: 34 
17:25:40 [Net] receive version message: 95.211.237.86:8333 "/Satoshi:0.14.0/" version: 70015 blocks: 487831 id: 35 
17:25:59 [Net] Id: 30 0 => 100 Ban threshold exceeded 
17:26:08 [Net] receive version message: 34.251.249.159:8333 "/Bitcoin ABC:0.14.6(EB8.0)/" version: 70015 blocks: 491227 id: 36 
17:26:12 [Net] Id: 21 0 => 100 Ban threshold exceeded 
17:26:14 [Net] receive version message: 46.105.116.19:8333 "/Satoshi:0.10.2/" version: 70002 blocks: 487831 id: 37 
17:26:15 [Net] receive version message: 93.104.208.119:8333 "/BUCash:1.1.1.1(EB16; AD12)/" version: 80003 blocks: 491227 id: 38 
17:26:18 [Net] Id: 38 0 => 100 Ban threshold exceeded 
17:26:31 [Net] Id: 13 0 => 100 Ban threshold exceeded 
    .926 [Net] receive version message: 88.99.186.13:8333 "/Satoshi:0.14.1/" version: 70015 blocks: 487831 id: 39 
17:26:32 [Net] receive version message: 104.198.83.171:8333 "/Satoshi:0.14.0/" version: 70015 blocks: 487831 id: 40 
17:26:44 [Net] receive version message: 88.150.192.17:8333 "/Satoshi:0.14.0/" version: 70015 blocks: 487832 id: 41

**Comment by fm444fm** [comment]
[debug.log.gz](https://github.com/bitcoinclassic/bitcoinclassic/files/1347391/debug.log.gz)

**Comment by fm444fm** [comment]
I am on ubuntu trusty, kernel 3.13.0-58-generic

**Comment by archon5880** [comment]
I still have the same problem.  I tried adding nodes manually, but it didn't help.  Is the only solution to wait for a newer release?

**Comment by zander** [comment]
New release is planned for tomorrow.

**Comment by archon5880** [comment]
Thanks, I just downloaded the 1.38 and now I am past the fork block up to August 3.

**Comment by archon5880** [comment]
Fully synced!!!

**Comment by zander** [comment]
Really happy to hear that :)

**Comment by fm444fm** [comment]
Yes, I can confirm it did work this time... ...unfortunately so late: lost too much profit being unable to move bch for so long
