### ISSUE TITLE
Nov 13 HF marking needed?

### ISSUE THREAD

**Issue by gubatron** [bitcoinclassic/bitcoinclassic#318]
will we be marking block 1510600000? (~Nov 13), [these guys marked it](https://reviews.bitcoinabc.org/D612) but I don't see anything else other than that these definitions being declared for now (not used)

`chainparams.cpp`:
```cpp
consensus.cashHardForkActivationTime = 1510600000;
```

`validation.cpp:`
```cpp
static bool IsCashHFEnabled(const Config &config, int64_t nMedianTimePast) {
    return nMedianTimePast >=
           config.GetChainParams().GetConsensus().cashHardForkActivationTime;
}

bool IsCashHFEnabled(const Config &config, const CBlockIndex *pindexPrev) {
    if (pindexPrev == nullptr) {
        return false;
    }

    return IsCashHFEnabled(config, pindexPrev->GetMedianTimePast());
}
```

**Comment by zander** [comment]
good question.

**Comment by BlinkyStitt** [comment]
The hard fork is getting pretty close. Who do we need to ask to figure this out?

**Comment by gubatron** [comment]
I think we can close this now. Segwit2X fork cancelled.

![screen shot 2017-11-08 at 11 10 33 am](https://user-images.githubusercontent.com/163977/32566563-8aea1462-c475-11e7-9622-31fec066c128.png)
