### ISSUE TITLE
make deploy does not work on OSX

### ISSUE THREAD

**Issue by lunokhod** [bitcoinclassic/bitcoinclassic#32]
I've successfully compiled the unix binaries from the master branch on OSX, however, I was not able to compile the OSX application via `make deploy`. I previously had no problems doing this either with core or XT

```
make deploy
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src qt/bitcoin-qt
  OBJCXXLD qt/bitcoin-qt
Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/bitcoin-qt] Error 1
make: *** [src/qt/bitcoin-qt] Error 2
```

**Comment by rromanchuk** [comment]
I'm on this now.

**Comment by codehalo** [comment]
I don't have this problem.
OSX version 10.11.2 / Qt5

Are you using Qt4?

Note that using Qt4 results in a broken UI:
https://github.com/bitcoinclassic/bitcoinclassic/blob/master/doc/build-osx.md

**Comment by FinalHash** [comment]
OSX Cert was just granted today. We will be using it to build QT-OSX

**Comment by rromanchuk** [comment]
Working well for me https://s3.amazonaws.com/rromanchuk-public/Bitcoin+Classic.dmg

**Comment by zander** [comment]
We stopped supporting the 0.11.2 branch, as such I'll close this report.
