### ISSUE TITLE
Concept for block scaling ( principal + extension )

### ISSUE THREAD

**Issue by bitcoinpaymentnetwork** [bitcoinclassic/bitcoinclassic#34]
Suppose a max block size of 100MB.
Miner solves a block and propagates 2MB( the principal ) plus an extension of 98MB in the sequence. The 2MB one is always sent first.

Nodes start the block (principal+extension) validating process, by then the principal is already fully known and possibly at least the extension's header is also already known by receiving the extension's first bytes. No need to wait the full extension for the block to be known. No hypothetical increased risks due to the block size?

Is something like this possible?

**Comment by jtoomim** [comment]
Github issues are not the right forum for shower thoughts. Take it to reddit.

**Comment by bitcoinpaymentnetwork** [comment]
ok

**Comment by bitcoinpaymentnetwork** [comment]
but i don't think developers will check it there

**Comment by jtoomim** [comment]
You mean people like me? It's true, I don't spend all of my day every day on reddit.

https://www.reddit.com/user/jtoomim/

I just spend enough time on reddit and replying to github stuff that it makes it hard for me to get much code written.

The point is that reddit has systems in place to help filter out the good ideas (which get upvotes) from the bad ones. Github does not.

**Comment by bitcoinpaymentnetwork** [comment]
Well. People who never fully analyzed Bitcoin Core code have no idea if it is a good idea or not and will be unable to vote up or down. I'm not praying for anyone to vote up and my post be read by Gavin or Garzik.

I've made posts like this on Bitcoin Core github and always get a reply instead of getting it closed with an offense, What's the point of calling it a "shower thought"? Does it make you feel superior? Everything was very immature.

**Comment by jtoomim** [comment]
I'm sorry for being impatient with you, but I get over 100 github notifications per day. I don't have time to answer every person's idea. I will be unsubscribing from this issue now.

**Comment by bitcoinpaymentnetwork** [comment]
I did not really hope you to reply, never heard of you before.
