### ISSUE TITLE
Fix our Continuous Integration

### ISSUE THREAD

**Issue by ripper234** [bitcoinclassic/bitcoinclassic#36]
I [edited](https://github.com/bitcoinclassic/bitcoinclassic/pull/35) the Readme.md file and got:

![image](https://cloud.githubusercontent.com/assets/172282/12440267/79d71812-bf42-11e5-9d06-d075b3bf7622.png)

https://travis-ci.org/bitcoinclassic/bitcoinclassic/builds/103527281

**Comment by transcats** [comment]
There's some SSL errors related to fetching the QR lib and Mac dependencies, plus an IPv6-related error with one of the tests.

Looks like Core runs the builds on a custom worker. Edit: or a legacy worker. Apparently the newer workers dropped IPv6 support.

**Comment by keo** [comment]
Fixed by #75
