### ISSUE TITLE
README.md needs updating to remove references to Bitcoin Core

### ISSUE THREAD

**Issue by rebroad** [bitcoinclassic/bitcoinclassic#39]
README.md needs updating to remove references to Bitcoin Core

**Comment by alfiedotwtf** [comment]
Already addressed in #18.

**Comment by OferE** [comment]
Not all references to bitcoin core were removed. This is really embarrassing...
The readme is the landing page of this project. This doesn't look professional.

**Comment by zander** [comment]
master hasn't been patched much, yet.

**Comment by dtto** [comment]
Yeah. there is a reference to core [here](https://github.com/bitcoinclassic/bitcoinclassic/blob/0.11.2/README.md#development-process). 

Also noticed when I fired the linux64 bins up that the splash screen states (C)Bitcoin Core which should probably be changed.

**Comment by zander** [comment]
Master stays 'untouched' for now. The active branches (0.12 and develop) are patched.
