### ISSUE TITLE
README.md Suggested Updates

### ISSUE THREAD

**Issue by ChainQuery** [bitcoinclassic/bitcoinclassic#53]
Here is a first crack at updating README.md, wanted to keep it in my own fork until I got some feedback...

https://github.com/ChainQuery/bitcoinclassic/blob/Readme-Update/README.md

**Comment by sugruedes** [comment]
You could probably merge the 2 headings 'What is Bitcoin' and 'What is Bitcoin Classic' into a single 'What is Bitcoin Classic' heading.

Good write up.

**Comment by chriswheeler** [comment]
I quite like the separation, it re-enforces the fact the Classic (or any one client) is not Bitcoin on its own. 

There have already been some changes made to readme.md in pull/46

**Comment by toomim** [comment]
This looks good! It's well-written, clear and professional.
