### ISSUE TITLE
Remove or change Core download link

### ISSUE THREAD

**Issue by stalane** [bitcoinclassic/bitcoinclassic#56]
![fucked](https://cloud.githubusercontent.com/assets/4401195/12674937/ce780170-c6c1-11e5-81aa-c47cf38011eb.png)

**Comment by chriswheeler** [comment]
Looks like this has been done.

**Comment by FinalHash** [comment]
Thanks for the heads up. It has been done. Closing issue now. We will again edit this when the builds are available. ETA 24-48 houirs
