### ISSUE TITLE
Add Satoshi Nakamoto's white paper to doc directory

### ISSUE THREAD

**Issue by jzbz** [bitcoinclassic/bitcoinclassic#64]
Andreas made a good case here https://github.com/bitcoin/bitcoin/pull/7443 for adding the original white paper to the repo. Thoughts?

**Comment by acidsploit** [comment]
Good idea.

**Comment by jojva** [comment]
I don't think whitepapers belong in a repo. They are not source code, they are not part of the software, and frankly this almost-religious cult of personality is unhealthy. The whitepaper is the **origin** of Bitcoin, not its future. That being said, I would be all for a link in the root README, because the whitepaper is basically "Bitcoin 101".

**Comment by zander** [comment]
I'd say its useful to include the whitepaper.

The argument that its not source code doesn't hold for immutable objects. Just like logos etc are in git, so can a document like the whitepaper.

While I do support the argument from Andreas about copyright, my personal reasoning is that everyone doing a clone of this bitcoin node should have access to the paper. Bitcoin as a conceptual protocol is still the best described by that paper. Which is sad in other ways (I'm working on a git repo with documentation to solve that issue).

**Comment by jojva** [comment]
Just for reference, there is a nice markdown version here: https://github.com/karask/shatoshi-paper/blob/master/markdown/bitcoin.md

**Comment by jzbz** [comment]
@jojva Thanks for the link to the markdown paper. With regards to the paper not being code, you are correct, however I believe including it would serve two important purposes, namely:
1. It resolves the licensing issue of the original white paper, returning it to the code base where it was once included by Satoshi. This is the issue that @aantonop was most concerned about. He was able to establish the provenance and original license of the paper to satisfy his publisher, however others in the future would be well served by having a clear source and and license for the file.
2. I believe the intention behind Bitcoin Classic is not merely a single code change which bumps block size up to 2MB, but a reaffirmation of the vision set out by Satoshi in the original white paper. Including it will help to distinguish the project much the way the code of conduct[1] attempts to shape the tone of discourse within the project.

[1] https://github.com/bitcoinclassic/bitcoinclassic/blob/master/CONTRIBUTING.md#codeofconduct

**Comment by davedx** [comment]
I agree. https://github.com/bitcoinclassic/bitcoinclassic/pull/96

**Comment by zander** [comment]
Closing, because done.
