### ISSUE TITLE
Compile Warning

### ISSUE THREAD

**Issue by eN0Rm** [bitcoinclassic/bitcoinclassic#81]
`main.cpp: In function 'bool FindBlockPos(CValidationState&, CDiskBlockPos&, unsigned int, unsigned int, uint64_t, bool)':
main.cpp:2707:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (nFile != nLastBlockFile) {
`

**Comment by jtoomim** [comment]
This issue is inherited from Core. This should be fixed in upstream or not at all. Fixing it on our side would make it harder to merge commits from Core in the future, and would not provide enough of an improvement to make that worthwhile.

**Comment by eN0Rm** [comment]
I can report it to them, but if it's fixed in core 0.12 then I'm not sure if they'll fix 0.11.2

**Comment by zander** [comment]
In order to release Classic as fast as possible the minimum change was made on top of the latest stable release of upstream. Which is 0.11.2.

There is a lot of good work done in the 0.12 branch that likely somehow will end up in Classic. Likely including fixes of this kind.
