### ISSUE TITLE
Windows x64 Executable Installer Creates Firewall Rules That Block Inbound TCP/UDP

### ISSUE THREAD

**Issue by tonesnotes** [bitcoinclassic/bitcoinclassic#82]

**Comment by ysangkok** [comment]
Are the installer scripts available so this can be verified?

**Comment by zander** [comment]
see doc/gitian-building.md for how to build Bitcoin.

I don't think this issue is a bug in the bitcoin client. When I started it I just got a request for creating such a rule. Which is normal for any (internet enabled) software running the first time on Windows.

**Comment by tonesnotes** [comment]
Retried a clean install after removing all existing bitcoin related firewall rules.
No issue this time.
Not client installer related.
