### ISSUE TITLE
Debian packages

### ISSUE THREAD

**Issue by C-Otto** [bitcoinclassic/bitcoinclassic#85]
I'd love to have a Debian package, possibly with a repository for (security) updates. I liked the Bitcoin XT approach very much.

**Comment by dtto** [comment]
+1

**Comment by Polve** [comment]
+1

**Comment by ghost** [comment]
+1

Would be nice to have simple to install Debian packages, or even something installable through ppa.

**Comment by notmandatory** [comment]
I just created pull request #99 to take the scripts XT uses to build debian packages and updates them for classic.  Anyone interested please take a look.

**Comment by ArturGoldyn** [comment]
+1
I'd like to have Debian 7, Debian 8 and newest Ubuntu.

**Comment by zander** [comment]
We have a PPA now, which should be useful for most.

**Comment by C-Otto** [comment]
Not for Debian users, which was the intention of this issue. Please reopen.

**Comment by zander** [comment]
I checked and asked someone smarter than me;

> the files and the repository follow a Debian standard, so adaptations needed are minimal and typically only in configuration, with the built package files being the same.
> 
> The primary difference is that the PPA enables the command `apt-add-repository` on Ubuntu, whereas on Debian you need a two-step approach with adding the repository to a config file and then installing its key.

so while I agree it is an continues ongoing job to make this better, please try the PPA.

**Comment by C-Otto** [comment]
GitHub notified my 8.5 years after your comment. I'm not using Bitcoin Classic anymore. For the record, I still don't think PPA repositories are suitable for Debian.
