### ISSUE TITLE
Release -win.zip big and redundant content

### ISSUE THREAD

**Issue by NiKiZe** [bitcoinclassic/bitcoinclassic#86]
It is ~116MB and has -win(32|64)-setup-unsigned.exe and -win-usigned.tar.gz that in turn seem to contain the same .exe files.

The -win(32|64).zip files should be published separately to make it easy for people to use it as a drop in replacement for core files without running the setup, or if anyone wants to run them as "portable"

**Comment by gavinandresen** [comment]
Agreed, there should be two windows zips containing the signed binaries and the source .tar.gz.

I'll fix, re-upload, and re-gpg-sign.

**Comment by gavinandresen** [comment]
Replaced the big, redundant zip with two .zips, and updated the gpg SHA256SUMS.asc file.

I forgot that only the -setup.exe files are Authenticode-code signed; I'm not going to change that. And I forgot github automagically creates source code links, so I didn't put that in the .zips, either.

**Comment by NiKiZe** [comment]
Thanks!
