### ISSUE TITLE
Cannot un-minimize from the Cinnamon system tray

### ISSUE THREAD

**Issue by jondo** [bitcoinclassic/bitcoinclassic#87]
I am on Linux Mint 17.3 64-bit, using your `bitcoin-0.11.2-linux64.tar.gz`.
After minimizing bitcoin-qt to the system tray, the appearing icon does not react on any mouse clicks to make the bitcoin-qt window reappear.

**Comment by jondo** [comment]
By the way, how can I now end the bitcoin-qt process? Is `killall bitcoin-qt` safe?

**Comment by zander** [comment]
Check your ~/.bitcoin/debug.log to see what your app is doing.

>  Is killall bitcoin-qt safe?

Yes, just don't use a specific signal.

**Comment by boris0** [comment]
I am also experiencing this same issue. I am running a different distro, but I am using the same DE, cinnamon 2.8.7-1 with bitcoin classic v0.12.0cl1. Running Bitcoin XT v0.11.0.0-2b918be (64-bit) on the same machine does not have this issue.

**Comment by boris0** [comment]
@jondo I'm running bitcoin classic v0.12.0cl1 on the latest Cinnamon 3.0.1, and it looks like the tray icon is functioning properly now.

**Comment by jondo** [comment]
Thank you, @boris0! I will test at a later time.

**Comment by zander** [comment]
I'm closing this as it seems to be fixed.
