### ISSUE TITLE
Official Amazon AWS AMI + Docker images

### ISSUE THREAD

**Issue by jzbz** [bitcoinclassic/bitcoinclassic#89]
I believe @jgarzik had floated the possibility[1] that there could be official AMI images produced. This, along with an official Docker image would be a great way of lowering the barrier for setting up a full node. Especially if the blockchain is bootstrapped so each new instance that gets spun up is not required to sync from scratch.

[1] https://twitter.com/jgarzik/status/688355566478032897

**Comment by tuxayo** [comment]
@jzbz Can you mention Docker in the name of the issue? So there wont be a duplicated issue created (Or maybe it's better to have this one for AWS and another for docker?)

**Comment by jzbz** [comment]
@tuxayo Done. If the devs think it is better to have two separate issues I'll change it back.

**Comment by tuxayo** [comment]
Somebody did a Docker Image https://hub.docker.com/r/bitcoinclassic/bitcoinclassic/
But I don't know is it's trustworthy.

**Comment by zander** [comment]
Others have picked up this ball, so closing.

**Comment by tuxayo** [comment]
> Others have picked up this ball

@zander Does that means that [this image](https://hub.docker.com/r/bitcoinclassic/bitcoinclassic/) gets an official endorsement?

And what about AWS AMI?

**Comment by rossigee** [comment]
Would be nice to know the answer to @tuxayo's question too. The Docker image linked to does not seem to have a Dockerfile publicly available (at least, not that I can readily find/see from that link). I don't yet feel comfortable running it on my hosts. It would be nice if there was an official/endorsed Dockerfile somewhere to base things on.

**Comment by juan-domenech** [comment]
I've done some work on [installing Classic on standard AWS Linux](http://blog.domenech.org/2016/04/how-to-install-bitcoin-classic-on-amazon-linux-aws-ec2.html).
It would be relatively easy to create a set of AMIs with an updated blockchain DB. 
Note 1: Two flavours are required (EC2 HVM and EC2 PV) for different EC2 instance types.
Note 2: Then a copy for each AWS Region (i.e.: Ireland, Virginia, Oregon, etc.).

**Comment by zander** [comment]
Thank juan!

To answer previous requests, the Classic team does not at this time have a solution we tested or are ready to endorse.

With that said, I want to point out that on a AWS or similar hosting solution you should not have any coins in your bitcoin wallet.  
If you also avoid that docker image doing anything other than just running the bitcoin image there is very little that you can lose.  So if you keep an eye on the logs of both Bitcoin and your AWS image (usage, connection count etc) you can rule out abusive software and you should be largely Ok running a well documented docker image.

**Comment by tuxayo** [comment]
@zander 

> So if you keep an eye on the logs of both Bitcoin and your AWS image (usage, connection count etc) you can rule out abusive software and you should be largely Ok running a well documented docker image.

A good strategy to sabotage a such a docker image would be to introduce an abusive software that isn't constantly active. So it may remain unnoticed until a strategic moment and by the time, a certain number of people would be running node based a such a hypothetical malicious image.

And since there are people motivated enough to pay to DDoS classic nodes, it would be normal for the most precocious of us to fear the hypothetical scenario described above and not trust binary software distributed by a unknown source.

Anyway, keep working on the stuff you prioritize the most. Thanks for your time and work :)
