### ISSUE TITLE
does not work when trying to mine with bfgminer

### ISSUE THREAD

**Issue by ERamseth** [bitcoinclassic/bitcoinclassic#90]
when trying to mine on bitcoin classic with bfgminer, i get the following error:

`blktmpl error: Unrecognized block version, and not allowed to reduce or force it`

and it never connects to the node via gbt.

I have worked around this by putting ckpool as standalone proxy mode in between.

Also, this is more likely something that needs to be changed in bfgminer or libblkmaker depending if classic HAS to advertise a new block version. Alternatively, luke-jr provided the following input on bitcointalk.org official bfgminer thread:

> If it isn't Classic-specific (ie, generalised), doesn't affect libblkmaker itself, and doesn't degrade Bitcoin support in any way.
> 
> But a more practical way would be to have Classic's bitcoind simply set sizelimit to 2 MB and use the version/force mutation in BIP 23.
> I think that would result in something that actually works with unmodified BFGMiner/libblkmaker.

full discussion here: https://bitcointalk.org/index.php?topic=877081.msg13758739#msg13758739

**Comment by zander** [comment]
I'd love to work with someone on the bfgminer project, should they require help. But this issue seems quite unlikely to be an issue in Bitcoin Classic.
