### ISSUE TITLE
Build ARMv7 binaries

### ISSUE THREAD

**Issue by jzbz** [bitcoinclassic/bitcoinclassic#94]
I'm running half a dozen Classic nodes on `Raspberry Pi 2 Model B` single-board computers, I wrote a small guide detailing the process of setting one up[1]. Currently the most tedious part of the process for a user wishing to bring up a node on a Pi is the compilation which takes a few hours. It would be great to have official binaries, since running binaries supplied by a third party is not ideal.

With official binaries we could provide users a simple `bash` script that turns a Pi into a full node in less than a minute.

[1] https://jz.bz/tar.jz/bitcoin-node/

**Comment by keo** [comment]
The 0.12 release contains official ARMv7 (armhf) binaries: https://github.com/bitcoinclassic/bitcoinclassic/releases/tag/v0.12.0cl1

And here's the guide to setting it up (with a 20 second bash script that does everything): https://www.reddit.com/r/btc/comments/49ogxg/how_to_run_bitcoin_classic_012_in_under_20/
